{
 "title": "Couchbase SDK Clients Copy",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "content": "<h2>Cluster Localhost</h2>\n" },
   "targets": [
    {}
   ]
  },
  { "title": "Couchbase Slow Ops Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "# Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 1, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(clusterUUID, instance) (db_couchbase_kv_connection{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KV Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(instance) (db_couchbase_client_kv_connections)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum KV Op/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(db_couchbase_operations_sum{outcome=\"Success\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg KV Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(db_couchbase_latency_bucket{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\", serviceType=\"KV\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KV Slow Ops",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(clusterUUID, instance) (db_couchbase_threshold_duration_count{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\", serviceType=\"KV\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Slow KV",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(clusterUUID, serviceType) (db_couchbase_threshold_server_bucket{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\", serviceType=\"KV\"} > 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% KV Slow Ops",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count by(clusterUUID, bucket, localId, operationId) (db_couchbase_threshold_server_bucket{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\"}) >= 1",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by(clusterUUID, bucket, localId, operationId) (db_couchbase_threshold_dispatch_bucket{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\"}) >= 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Slow Ops",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "db_couchbase_threshold_duration_count{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\", serviceType=\"KV\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Slow Query ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "db_couchbase_threshold_server_duration{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\", serviceType=\"QUERY\"} >= 10",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Clients Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "last_over_time(db_couchbase_kv_connection{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by(clusterUUID, job) (db_couchbase_kv_connection{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "system_cpu_usage{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\"} * 100.0",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_memory_used_bytes{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "count_over_time(db_couchbase_threshold_server_sum{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\", serviceType=\"KV\"}[5m]) >= 10",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (clusterUUID, instance) (sum_over_time(db_couchbase_threshold_ops_total{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\", serviceType=\"KV\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(clusterUUID, job) (avg_over_time(db_couchbase_latency_sum{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\", serviceType=\"KV\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(clusterUUID, instance) (sum_over_time(db_couchbase_threshold_ops_total{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\", serviceType=\"QUERY\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "\navg by(clusterUUID, job) (avg_over_time(db_couchbase_latency_sum{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\", serviceType=\"QUERY\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(clusterUUID, job) (db_couchbase_threshold_timeout_max{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\", serviceType=\"KV\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(clusterUUID, job) (db_couchbase_threshold_timeout_max{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\", serviceType=\"QUERY\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TOP slow KV Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "topk by(clusterUUID, instance, application) (5, db_couchbase_threshold_duration_bucket{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\", serviceType=\"KV\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk by(clusterUUID, application, instance) (5, db_couchbase_threshold_server_bucket{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\", serviceType=\"KV\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk by(clusterUUID, application, instance) (5, db_couchbase_threshold_dispatch_bucket{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\", serviceType=\"KV\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk by(clusterUUID, application, instance) (5, db_couchbase_threshold_encode_bucket{clusterUUID=\"b902e30a10fbb1fa84718045a147eaf2\", serviceType=\"KV\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}