{
 "title": "Alertmanager Overview",
 "description": "Dashboard showing Prometheus Alertmanager metrics for observing status of the cluster and possible debbuging.",
 "tags": [
  "alertmanager",
  "prometheus",
  "alerting",
  "alerts"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(alertmanager_build_info, instance)"
    }
   },
   {
    "name": "handler",
    "query": {
     "query": "label_values(alertmanager_http_request_duration_seconds_bucket{instance=\"$node\",handler!~\".*(\\\\.ico|\\\\.js).*\"}, handler)"
    }
   },
   {
    "name": "integration",
    "query": {
     "query": "label_values(alertmanager_notification_latency_seconds_bucket{instance=\"$node\"}, integration)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node",
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "<br><h1 style=\"text-align:center;\">$node</h1>"
   },
   "targets": [
    {
     "expr": "alertmanager_build_info{instance=~\"$node\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Build Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmanager_build_info{instance=~\"$node\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Start time of the process since unix epoch in seconds.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=~\"$node\",job=~\".*alert-?manager.*\"}"
    }
   ]
  },
  {
   "title": "Last Config Reload",
   "type": "stat",
   "description": "Timestamp of the last successful configuration reload.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - alertmanager_config_last_reload_success_timestamp_seconds{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "stat",
   "description": "Current number of active alerts.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmanager_alerts{state=\"active\", instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Firing Alerts/sec",
   "type": "stat",
   "description": "The total number of received alerts that are firing",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(alertmanager_alerts_received_total{status=\"firing\",instance=~\"$node\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Resolved Alerts",
   "type": "stat",
   "description": "The total number of received alerts that are resolved in the time range",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(alertmanager_alerts_received_total{status=\"resolved\",instance=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Suppressed Alerts",
   "type": "stat",
   "description": "Current number of suppressed alerts.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmanager_alerts{state=\"suppressed\", instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Clustering Enabled",
   "type": "stat",
   "description": "Indicates whether the clustering is enabled or not.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmanager_cluster_enabled{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Integrations Receivers",
   "type": "stat",
   "description": "Number of configured receivers",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmanager_receivers{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Integrations Configured",
   "type": "stat",
   "description": "Number of configured integrations.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmanager_integrations{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Last Config Reload Successful",
   "type": "stat",
   "description": "Whether the last configuration reload attempt was successful.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmanager_config_last_reload_successful{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Active Silences",
   "type": "stat",
   "description": "Current number of active silences.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmanager_silences{state=\"active\", instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Invalid Alerts",
   "type": "stat",
   "description": "The total number of received alerts that were invalid.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(alertmanager_alerts_invalid_total{instance=~\"$node\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "HTTP Request Limit Exceeded",
   "type": "stat",
   "description": "Total number of times an HTTP request failed because the concurrency limit was reached.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(alertmanager_http_concurrency_limit_exceeded_total{instance=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Notification Log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Notification Log Queries",
     "type": "timeseries",
     "description": "Number of notification log queries were received and errored.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "increase(alertmanager_nflog_queries_total{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "Queries"
      },
      {
       "expr": "increase(alertmanager_nflog_query_errors_total{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "Failed"
      }
     ]
    },
    {
     "title": "Nflog Query Evaluation Latency",
     "type": "heatmap",
     "description": "Duration of notification log query evaluation.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
     "targets": [
      {
       "expr": "sum by(le) (increase(alertmanager_nflog_query_duration_seconds_bucket{instance=~\"$node\"}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Nflog Query Evaluation Latency -  Percentiles",
     "type": "timeseries",
     "description": "Duration of notification log query evaluation.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le, instance) (increase(alertmanager_nflog_query_duration_seconds_bucket{instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{instance}} - 50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, instance) (increase(alertmanager_nflog_query_duration_seconds_bucket{instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{instance}} - 90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le, instance) (increase(alertmanager_nflog_query_duration_seconds_bucket{instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{instance}} - 99th Percentile"
      }
     ]
    },
    {
     "title": "Nflog Snapshot Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "alertmanager_nflog_snapshot_size_bytes{instance=~\"$node\"}",
       "legendFormat": "{{instance}} - Snapshot Size"
      }
     ]
    },
    {
     "title": "Nflog Snapshot Duration",
     "type": "timeseries",
     "description": "Duration of the last notification log snapshot.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(alertmanager_nflog_snapshot_duration_seconds_sum{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - Snapshot duration"
      }
     ]
    },
    {
     "title": "Notification Log GC Time",
     "type": "timeseries",
     "description": "Duration of the last notification log garbage collection cycle.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(alertmanager_nflog_gc_duration_seconds_sum{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "Duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Notifications Integrations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$integration - Total Requests Attempted",
     "type": "timeseries",
     "description": "The total number of attempted notifications.",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
     "repeat": "integration",
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(alertmanager_notifications_total{instance=~\"$node\",integration=~\"$integration\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - Requests"
      }
     ]
    },
    {
     "title": "$integration - Total Requests / Failures",
     "type": "timeseries",
     "description": "The total number of attempted notification requests and failed requests",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
     "repeat": "integration",
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(alertmanager_notification_requests_total{instance=~\"$node\",integration=~\"$integration\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - Requests"
      },
      {
       "expr": "rate(alertmanager_notifications_failed_total{instance=~\"$node\",integration=~\"$integration\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - Failed"
      }
     ]
    },
    {
     "title": "$integration - Notification Latency Heatmap",
     "type": "heatmap",
     "description": "The latency of notifications in seconds.",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
     "repeat": "integration",
     "targets": [
      {
       "expr": "sum by(le) (increase(alertmanager_notification_latency_seconds_bucket{instance=~\"$node\",integration=~\"$integration\"}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "$integration - Notification Latency Percentiles",
     "type": "timeseries",
     "description": "The latency of notifications in seconds.",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
     "repeat": "integration",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le, instance) (increase(alertmanager_notification_latency_seconds_bucket{instance=~\"$node\",integration=~\"$integration\"}[$__rate_interval])))",
       "legendFormat": "{{instance}} - 50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, instance) (increase(alertmanager_notification_latency_seconds_bucket{instance=~\"$node\",integration=~\"$integration\"}[$__rate_interval])))",
       "legendFormat": "{{instance}} - 90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le, instance) (increase(alertmanager_notification_latency_seconds_bucket{instance=~\"$node\",integration=~\"$integration\"}[$__rate_interval])))",
       "legendFormat": "{{instance}} - 99th Percentile"
      }
     ]
    }
   ]
  },
  {
   "title": "Silences",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Silences by State",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "alertmanager_silences{instance=~\"$node\"}",
       "legendFormat": "{{instance}} - {{state}}"
      }
     ]
    },
    {
     "title": "Silence Query Latency",
     "type": "heatmap",
     "description": "Duration of silence query evaluation.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
     "targets": [
      {
       "expr": "sum by(le) (increase(alertmanager_silences_query_duration_seconds_bucket{instance=~\"$node\"}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Silence Query Latency - Percentiles",
     "type": "timeseries",
     "description": "Duration of silence query evaluation.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le, instance) (increase(alertmanager_silences_query_duration_seconds_bucket{instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{instance}} - 50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, instance) (increase(alertmanager_silences_query_duration_seconds_bucket{instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{instance}} - 90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le, instance) (increase(alertmanager_silences_query_duration_seconds_bucket{instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{instance}} - 99th Percentile"
      }
     ]
    },
    {
     "title": "Silence Queries/sec",
     "type": "timeseries",
     "description": "How many silence queries were received and failed",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(alertmanager_silences_queries_total{instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - Silences"
      },
      {
       "expr": "sum(rate(alertmanager_silences_query_errors_total{instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - Failed"
      }
     ]
    },
    {
     "title": "Silences Snapshot Duration",
     "type": "timeseries",
     "description": "Duration of the last silence snapshot.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(alertmanager_silences_snapshot_duration_seconds_sum{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - Silences snapshot duration"
      }
     ]
    },
    {
     "title": "Silences GC Time",
     "type": "timeseries",
     "description": "Duration of the last silence garbage collection cycle.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(alertmanager_silences_gc_duration_seconds_sum{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "Duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Active Alerts",
     "type": "timeseries",
     "description": "Number of alerts by state such as `active`, `suppressed` etc.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(alertmanager_alerts{instance=~\"$node\",state=\"active\"}) by (instance)",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(alertmanager_alerts{instance=~\"$node\",state=\"suppressed\"}) by (instance)",
       "legendFormat": "Suppressed"
      }
     ]
    },
    {
     "title": "Received alerts by status",
     "type": "timeseries",
     "description": "Number of received alerts from Prometheus by status `firing` on positive axis and `resolved` on negative axis.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(alertmanager_alerts_received_total{instance=~\"$node\"}[$__rate_interval])) by (instance, status)",
       "legendFormat": "{{instance}} - {{ status }}"
      }
     ]
    },
    {
     "title": "Suppressed Alerts",
     "type": "timeseries",
     "description": "Current number of suppressed alerts.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "alertmanager_alerts{state=\"suppressed\", instance=~\"$node\"}",
       "legendFormat": "{{instance}} - Suppressed"
      }
     ]
    },
    {
     "title": "Alert Processing Latency",
     "type": "timeseries",
     "description": "Summary of latencies for the processing of alerts.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(alertmanager_dispatcher_alert_processing_duration_seconds_sum{instance=~\"$node\"}[$__rate_interval])\n/\nrate(alertmanager_dispatcher_alert_processing_duration_seconds_count{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{ status }}"
      }
     ]
    },
    {
     "title": "Aggregation Groups",
     "type": "stat",
     "description": "Number of active aggregation groups",
     "gridPos": { "h": 6, "w": 3, "x": 8, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "alertmanager_dispatcher_aggregation_groups{instance=~\"$node\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Members",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Clusterhealth score",
     "type": "timeseries",
     "description": "Shows cluster score representing cluster health. From Hashicorps official documentation: \n> This metric describes a node's perception of its own health based on how well it is meeting the soft real-time requirements of the protocol. This metric ranges from 0 to 8, where 0 indicates \"totally healthy\".\n\nFor more info see https://www.consul.io/docs/agent/telemetry.html#cluster-health",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(alertmanager_cluster_health_score) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Cluster members count",
     "type": "timeseries",
     "description": "Shows gossip cluster members count in time and failing peers in case of any in red color.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "alertmanager_cluster_members{instance=~\"$node\"}",
       "legendFormat": "Number of cluster members"
      },
      {
       "expr": "alertmanager_cluster_failed_peers{instance=~\"$node\"}",
       "legendFormat": "Number of failed peers"
      }
     ]
    },
    {
     "title": "Cluster reconnections",
     "type": "timeseries",
     "description": "On positive axis is number of attempts to reconnect the cluster. On negative axis if number of failed attempts.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(alertmanager_cluster_reconnections_total{instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - Successful reconnections"
      },
      {
       "expr": "sum(increase(alertmanager_cluster_reconnections_failed_total{instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - Failed reconnections"
      }
     ]
    },
    {
     "title": "Cluster peers left/joined",
     "type": "timeseries",
     "description": "On positive axis shows number of peers that joined the cluster and on negative axis number of peers that left the cluster.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(alertmanager_cluster_peers_left_total{instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - Cluster joined peers"
      },
      {
       "expr": "sum(increase(alertmanager_cluster_peers_joined_total{instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - Cluster left peers"
      }
     ]
    },
    {
     "title": "Cluster messages size",
     "type": "timeseries",
     "description": "On positive axis is size of sent cluster messages by type `update`  or `full_state` and on negative axis the same for received messages.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(increase(alertmanager_cluster_messages_sent_size_total{instance=~\"$node\"}[$__rate_interval])) by (instance, msg_type)",
       "legendFormat": "{{instance}} - sent {{msg_type}}"
      },
      {
       "expr": "sum(increase(alertmanager_cluster_messages_received_size_total{instance=~\"$node\"}[$__rate_interval])) by (instance, msg_type)",
       "legendFormat": "{{instance}} - received {{msg_type}}"
      }
     ]
    },
    {
     "title": "Cluster messages count",
     "type": "timeseries",
     "description": "On positive axis is number of sent cluster messages by type `update`  or `full_state` and on negative axis the same for received messages.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(alertmanager_cluster_messages_sent_total{instance=~\"$node\"}[$__rate_interval])) by (instance, msg_type)",
       "legendFormat": "{{instance}} - sent {{msg_type}}"
      },
      {
       "expr": "sum(increase(alertmanager_cluster_messages_received_total{instance=~\"$node\"}[$__rate_interval])) by (instance, msg_type)",
       "legendFormat": "{{instance}} - received {{msg_type}}"
      }
     ]
    },
    {
     "title": "Cluster messages queue",
     "type": "timeseries",
     "description": "On positive axis is number of queued cluster messages and on negative axis number of pruned messages.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(alertmanager_cluster_messages_pruned_total{instance=~\"$node\"}) by (instance)",
       "legendFormat": "{{instance}} - Pruned messaged"
      },
      {
       "expr": "sum(alertmanager_cluster_messages_queued{instance=~\"$node\"}) by (instance)",
       "legendFormat": "{{instance}} - Queued messages"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Handler Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$handler - Request Times",
     "type": "heatmap",
     "description": "Histogram of latencies for HTTP requests.",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
     "repeat": "handler",
     "targets": [
      {
       "expr": "sum by(le) (increase(alertmanager_http_request_duration_seconds_bucket{instance=\"$node\",handler=\"$handler\"}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "$handler - Request Duration Percentiles",
     "type": "timeseries",
     "description": "Histogram of latencies for HTTP requests.",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
     "repeat": "handler",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (increase(alertmanager_http_request_duration_seconds_bucket{instance=\"$node\",handler=\"$handler\"}[$__rate_interval])))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (increase(alertmanager_http_request_duration_seconds_bucket{instance=\"$node\",handler=\"$handler\"}[$__rate_interval])))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(alertmanager_http_request_duration_seconds_bucket{instance=\"$node\",handler=\"$handler\"}[$__rate_interval])))",
       "legendFormat": "99th Percentile"
      }
     ]
    },
    {
     "title": "$handler - Request Size",
     "type": "heatmap",
     "description": "Histogram of response size for HTTP requests.",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
     "repeat": "handler",
     "targets": [
      {
       "expr": "sum by(le) (increase(alertmanager_http_response_size_bytes_bucket{instance=\"$node\",handler=\"$handler\"}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "$handler - Response Size Percentiles",
     "type": "timeseries",
     "description": "Histogram of response size for HTTP requests.",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
     "repeat": "handler",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (increase(alertmanager_http_response_size_bytes_bucket{instance=\"$node\",handler=\"$handler\"}[$__rate_interval])))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (increase(alertmanager_http_response_size_bytes_bucket{instance=\"$node\",handler=\"$handler\"}[$__rate_interval])))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(alertmanager_http_response_size_bytes_bucket{instance=\"$node\",handler=\"$handler\"}[$__rate_interval])))",
       "legendFormat": "99th Percentile"
      }
     ]
    }
   ]
  },
  {
   "title": "Gossip Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Count of oversized gossip messages",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(alertmanager_oversized_gossip_message_sent_total{instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - {{key}}"
      },
      {
       "expr": "sum(increase(alertmanager_oversized_gossip_message_dropped_total{instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - dropped {{key}}"
      },
      {
       "expr": "sum(increase(alertmanager_oversized_gossip_message_failure_total{instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - failed {{key}}"
      }
     ]
    },
    {
     "title": "Duration of oversized gossip messages",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1,rate(alertmanager_oversize_gossip_message_duration_seconds_bucket{instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} - {{key}}"
      }
     ]
    },
    {
     "title": "Number of  propagated gossip messages",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(alertmanager_silences_gossip_messages_propagated_total{instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - silences"
      },
      {
       "expr": "sum(increase(alertmanager_nflog_gossip_messages_propagated_total{instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}} - nf_log"
      }
     ]
    },
    {
     "title": "Notification Log Received  Gossip Messages",
     "type": "timeseries",
     "description": "Number of received gossip messages that have been further gossiped.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(alertmanager_nflog_gossip_messages_propagated_total{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - Messages"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Process CPU Usage",
     "type": "gauge",
     "description": "Total user and system CPU time spent in seconds.",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{instance=\"$node\"}[$__rate_interval])  "
      }
     ]
    },
    {
     "title": "Open File Descriptors ",
     "type": "stat",
     "description": "Number of open file descriptors.",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_open_fds{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "FD Utilization",
     "type": "gauge",
     "description": "Number of open file descriptors / Maximum number of open file descriptors",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_open_fds{instance=\"$node\"} / process_max_fds{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "Process Resident Memory",
     "type": "stat",
     "description": "Resident memory size in bytes.",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "Process Virtual Memory",
     "type": "stat",
     "description": "Virtual memory size in bytes.",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "Process Uptime",
     "type": "stat",
     "description": "Start time of the process since unix epoch in seconds.",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
     "repeat": "node",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{instance=~\"$node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connection Tracking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "net_conntrack_dialer_conn_attempted_total",
     "type": "timeseries",
     "description": "Total number of connections attempted by the given dialer a given name.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "increase(net_conntrack_dialer_conn_attempted_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{dialer_name}}"
      }
     ]
    },
    {
     "title": "net_conntrack_dialer_conn_closed_total",
     "type": "timeseries",
     "description": "Total number of connections closed which originated from the dialer of a given name.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
     "targets": [
      {
       "expr": "increase(net_conntrack_dialer_conn_closed_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{dialer_name}}"
      }
     ]
    },
    {
     "title": "net_conntrack_dialer_conn_established_total",
     "type": "timeseries",
     "description": "Total number of connections successfully established by the given dialer a given name.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
     "targets": [
      {
       "expr": "increase(net_conntrack_dialer_conn_established_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{dialer_name}}"
      }
     ]
    },
    {
     "title": "net_conntrack_dialer_conn_failed_total",
     "type": "timeseries",
     "description": "Total number of connections failed to dial by the dialer a given name.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum by (dialer_name, reason) (increase(net_conntrack_dialer_conn_failed_total{instance=\"$node\"}[$__rate_interval])) ",
       "legendFormat": "{{dialer_name}} - {{reason}}"
      }
     ]
    },
    {
     "title": "Listener Accepted and Closed Connections",
     "type": "timeseries",
     "description": "Total number of connections opened to the listener of a given name.\n\nTotal number of connections closed that were made to the listener of a given name.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(net_conntrack_dialer_conn_established_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{dialer_name}} - open"
      },
      {
       "expr": "increase(net_conntrack_dialer_conn_closed_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{dialer_name}} - closed"
      }
     ]
    }
   ]
  }
 ]
}