{
 "title": "Couchbase Logs - Audit Log Overview",
 "tags": [
  "couchbase",
  "logs",
  "audit",
  "loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({file=\"slow_query.log\"}, couchbase_cluster_name)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values({file=\"slow_query.log\",couchbase_cluster_name=~\"$cluster\"}, couchbase_node)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Audit Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All Audit Events/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (couchbase_node) (\n  rate(\n    {couchbase_cluster_name=\"$cluster\", file=\"audit.log\", couchbase_node=~\"$node\"} [$interval]\n  )\n)",
     "legendFormat": "{{couchbase_node}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "Audit Events by Bucket",
   "type": "timeseries",
   "description": "Total audit events for bucket within the interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bucket) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"audit.log\", couchbase_node=~\"$node\",bucket=~\".+\"} [$interval]\n    | bucket!=\"undefined\"\n  )\n)",
     "legendFormat": "{{bucket}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "Authentication/Authorization Failure Events",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by(name) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"audit.log\", couchbase_node=~\"$node\"} \n    | json\n    | name=~\"(?i).+failure.*\" [$__range]\n  )\n)",
     "legendFormat": "{{name}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "Audit Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (couchbase_node) (\n  bytes_rate(\n    {couchbase_cluster_name=\"$cluster\", file=\"audit.log\", couchbase_node=~\"$node\"} | __error__=\"\"  [$interval]\n  )\n)",
     "legendFormat": "{{couchbase_node}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "Audit Events by Component",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum by(component) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"audit.log\", couchbase_node=~\"$node\"} \n    | json\n    | __error__=\"\" [$__interval]\n  )\n)",
     "legendFormat": "{{name}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "Audit Events by User",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum by(real_userid_user) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"audit.log\", couchbase_node=~\"$node\"} \n    | json\n    | __error__=\"\" [$__interval]\n  )\n)",
     "legendFormat": "{{name}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "Service Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "REST API Events (Total)",
     "type": "timeseries",
     "description": "The number of REST API events in the threshold",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (name) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"audit.log\", couchbase_node=~\"$node\"} \n    | json \n    | component=\"rest\" [$interval]\n  )\n)",
       "legendFormat": "{{couchbase_node}}",
       "resolution": 5
      }
     ]
    },
    {
     "title": "Data Service Events (Total)",
     "type": "timeseries",
     "description": "The number of Data Service events in the threshold",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (name) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"audit.log\", couchbase_node=~\"$node\"} \n    | json \n    | component=\"data\" [$interval]\n  )\n)",
       "legendFormat": "{{name}}",
       "resolution": 5
      }
     ]
    },
    {
     "title": "XDCR Service Events (Total)",
     "type": "timeseries",
     "description": "The number of XDCR Service events in the threshold",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (name) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"audit.log\", couchbase_node=~\"$node\"} \n    | json \n    | component=\"xdcr\" [$interval]\n  )\n)",
       "legendFormat": "{{name}}",
       "resolution": 5
      }
     ]
    },
    {
     "title": "Index and Query Service Events (Total)",
     "type": "timeseries",
     "description": "The number of Index and Query Service events in the threshold",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (name) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"audit.log\", couchbase_node=~\"$node\"} \n    | json \n    | component=\"index-query\" [$interval]\n  )\n)",
       "legendFormat": "{{name}}",
       "resolution": 5
      }
     ]
    },
    {
     "title": "Search Service Events (Total)",
     "type": "timeseries",
     "description": "The number of Search Service events in the threshold",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (name) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"audit.log\", couchbase_node=~\"$node\"} \n    | json \n    | component=\"search\" [$interval]\n  )\n)",
       "legendFormat": "{{name}}",
       "resolution": 5
      }
     ]
    },
    {
     "title": "Eventing Service Events (Total)",
     "type": "timeseries",
     "description": "The number of Eventing Service events in the threshold",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (name) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"audit.log\", couchbase_node=~\"$node\"} \n    | json \n    | component=\"eventing\" [$interval]\n  )\n)",
       "legendFormat": "{{name}}",
       "resolution": 5
      }
     ]
    },
    {
     "title": "Analytics Service Events (Total)",
     "type": "timeseries",
     "description": "The number of Analytics Service events in the threshold",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (name) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"audit.log\", couchbase_node=~\"$node\"} \n    | json \n    | component=\"analytics\" [$interval]\n  )\n)",
       "legendFormat": "{{name}}",
       "resolution": 5
      }
     ]
    },
    {
     "title": "Backup Service Events (Total)",
     "type": "timeseries",
     "description": "The number of Backup Service events in the threshold",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (name) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"audit.log\", couchbase_node=~\"$node\"} \n    | json \n    | component=\"backup\" [$interval]\n  )\n)",
       "legendFormat": "{{name}}",
       "resolution": 5
      }
     ]
    },
    {
     "title": "Unknown Events (Total)",
     "type": "timeseries",
     "description": "The number of Backup Service events in the threshold",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (name) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"audit.log\", couchbase_node=~\"$node\"} \n    | json \n    | component=\"unknown\" [$interval]\n  )\n)",
       "legendFormat": "{{name}}",
       "resolution": 5
      }
     ]
    }
   ]
  }
 ]
}