{
 "title": "Couchbase // Prometheus Blackbox Exporter",
 "description": "Prometheus Blackbox Exporter Overview",
 "tags": [
  "blackbox",
  "prometheus",
  "probe"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(probe_success, cluster_name)"
    }
   },
   {
    "name": "target",
    "label": "Target",
    "query": {
     "query": "label_values(probe_success{cluster_name=~\"$cluster\"}, instance)"
    }
   },
   {
    "name": "port",
    "label": "Port",
    "query": {
     "query": "label_values(probe_success{cluster_name=~\"$cluster\",instance=~\"$target\"}, port)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Probes",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "probe_success{namespace=\"database\",cluster_name=\"$cluster\",instance=~\"$target\",port=~\"$port\"}",
     "legendFormat": "Success"
    },
    {
     "expr": "probe_http_status_code{namespace=\"database\",cluster_name=\"$cluster\",instance=~\"$target\",port=~\"$port\"}",
     "legendFormat": "Status Code"
    },
    {
     "expr": "probe_duration_seconds{namespace=\"database\",cluster_name=\"$cluster\",instance=~\"$target\",port=~\"$port\"}",
     "legendFormat": "Probe Duration"
    },
    {
     "expr": "probe_dns_lookup_time_seconds{namespace=\"database\",cluster_name=\"$cluster\",instance=~\"$target\",port=~\"$port\"}",
     "legendFormat": "DNS Lookup"
    },
    {
     "expr": "probe_http_version{namespace=\"database\",cluster_name=\"$cluster\",instance=~\"$target\",port=~\"$port\"}",
     "legendFormat": "HTTP Version"
    },
    {
     "expr": "probe_ip_protocol{namespace=\"database\",cluster_name=\"$cluster\",instance=~\"$target\",port=~\"$port\"}      ",
     "legendFormat": "IP Protocol"
    }
   ]
  },
  { "title": "Target: $target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "target" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_success{namespace=\"database\",cluster_name=\"$cluster\",instance=~\"$target\",port=~\"$port\"})",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Probes Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{namespace=\"database\",cluster_name=\"$cluster\",instance=~\"$target\",port=~\"$port\"}==1)",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Probes Down",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{namespace=\"database\",cluster_name=\"$cluster\",instance=~\"$target\",port=~\"$port\"}==0)",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Avg. Probe Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{namespace=\"database\",cluster_name=\"$cluster\",instance=~\"$target\",port=~\"$port\"})",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Avg. DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{namespace=\"database\",cluster_name=\"$cluster\",instance=~\"$target\",port=~\"$port\"})",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "SSL Expiration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_ssl_earliest_cert_expiry{namespace=\"database\",cluster_name=\"$cluster\",instance=~\"$target\",port=~\"$port\"}) - time()",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "TLS Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (version) (probe_tls_version_info{namespace=\"database\",cluster_name=\"$cluster\",instance=~\"$target\",port=~\"$port\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "IP Protocol",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(probe_ip_protocol{namespace=\"database\",cluster_name=\"$cluster\",instance=~\"$target\",port=~\"$port\"})",
     "legendFormat": "ip_version"
    }
   ]
  },
  { "title": "Target: $target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_success{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Probes Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{namespace=\"database\",instance=~\"$target\"}==1)",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Probes Down",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{namespace=\"database\",instance=~\"$target\"}==0)",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Avg. Probe Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Avg. DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "SSL Expiration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_ssl_earliest_cert_expiry{namespace=\"database\",instance=~\"$target\"}) - time()",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "TLS Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (version) (probe_tls_version_info{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "IP Protocol",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(probe_ip_protocol{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "ip_version"
    }
   ]
  },
  { "title": "Target: $target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_success{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Probes Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{namespace=\"database\",instance=~\"$target\"}==1)",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Probes Down",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{namespace=\"database\",instance=~\"$target\"}==0)",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Avg. Probe Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Avg. DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "SSL Expiration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_ssl_earliest_cert_expiry{namespace=\"database\",instance=~\"$target\"}) - time()",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "TLS Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (version) (probe_tls_version_info{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "IP Protocol",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(probe_ip_protocol{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "ip_version"
    }
   ]
  },
  { "title": "Target: $target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_success{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Probes Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{namespace=\"database\",instance=~\"$target\"}==1)",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Probes Down",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{namespace=\"database\",instance=~\"$target\"}==0)",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Avg. Probe Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Avg. DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "SSL Expiration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_ssl_earliest_cert_expiry{namespace=\"database\",instance=~\"$target\"}) - time()",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "TLS Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (version) (probe_tls_version_info{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "IP Protocol",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(probe_ip_protocol{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "ip_version"
    }
   ]
  },
  { "title": "Target: $target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_success{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Probes Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{namespace=\"database\",instance=~\"$target\"}==1)",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Probes Down",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{namespace=\"database\",instance=~\"$target\"}==0)",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Avg. Probe Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Avg. DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "SSL Expiration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_ssl_earliest_cert_expiry{namespace=\"database\",instance=~\"$target\"}) - time()",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "TLS Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (version) (probe_tls_version_info{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "IP Protocol",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(probe_ip_protocol{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "ip_version"
    }
   ]
  },
  { "title": "Target: $target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_success{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Probes Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{namespace=\"database\",instance=~\"$target\"}==1)",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Probes Down",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{namespace=\"database\",instance=~\"$target\"}==0)",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Avg. Probe Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Avg. DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "SSL Expiration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_ssl_earliest_cert_expiry{namespace=\"database\",instance=~\"$target\"}) - time()",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "TLS Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (version) (probe_tls_version_info{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "IP Protocol",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(probe_ip_protocol{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "ip_version"
    }
   ]
  },
  { "title": "Target: $target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_success{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Probes Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{namespace=\"database\",instance=~\"$target\"}==1)",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Probes Down",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{namespace=\"database\",instance=~\"$target\"}==0)",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Avg. Probe Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Avg. DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "SSL Expiration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_ssl_earliest_cert_expiry{namespace=\"database\",instance=~\"$target\"}) - time()",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "TLS Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (version) (probe_tls_version_info{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "IP Protocol",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(probe_ip_protocol{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "ip_version"
    }
   ]
  },
  { "title": "Target: $target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_success{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Probes Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{namespace=\"database\",instance=~\"$target\"}==1)",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Probes Down",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{namespace=\"database\",instance=~\"$target\"}==0)",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Avg. Probe Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Avg. DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "SSL Expiration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_ssl_earliest_cert_expiry{namespace=\"database\",instance=~\"$target\"}) - time()",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "TLS Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (version) (probe_tls_version_info{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "IP Protocol",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(probe_ip_protocol{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "ip_version"
    }
   ]
  },
  { "title": "Target: $target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_success{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Probes Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{namespace=\"database\",instance=~\"$target\"}==1)",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Probes Down",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{namespace=\"database\",instance=~\"$target\"}==0)",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Avg. Probe Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Avg. DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "SSL Expiration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_ssl_earliest_cert_expiry{namespace=\"database\",instance=~\"$target\"}) - time()",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "TLS Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (version) (probe_tls_version_info{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "IP Protocol",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(probe_ip_protocol{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "ip_version"
    }
   ]
  },
  { "title": "Target: $target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_success{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Probes Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{namespace=\"database\",instance=~\"$target\"}==1)",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Probes Down",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{namespace=\"database\",instance=~\"$target\"}==0)",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Avg. Probe Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Avg. DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "SSL Expiration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_ssl_earliest_cert_expiry{namespace=\"database\",instance=~\"$target\"}) - time()",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "TLS Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (version) (probe_tls_version_info{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "IP Protocol",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(probe_ip_protocol{namespace=\"database\",instance=~\"$target\"})",
     "legendFormat": "ip_version"
    }
   ]
  },
  {
   "title": "Timings and Results",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Probe Duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "probe_duration_seconds{namespace=\"database\",instance=~\"$target\"}",
       "legendFormat": "{{instance}}:{{port}}"
      }
     ]
    },
    {
     "title": "DNS Lookup",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "probe_dns_lookup_time_seconds{namespace=\"database\",instance=~\"$target\"}",
       "legendFormat": "{{instance}}:{{port}}"
      }
     ]
    },
    {
     "title": "HTTP Status Code",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "probe_http_status_code{namespace=\"database\",instance=~\"$target\"}",
       "legendFormat": "{{instance}}:{{port}})"
      }
     ]
    },
    {
     "title": "HTTP Duration (phase = $phase)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "probe_http_duration_seconds{namespace=\"database\",instance=~\"$target\"}",
       "legendFormat": "{{instance}} ({{endpoint}}) - {{ phase }}"
      }
     ]
    }
   ]
  }
 ]
}