{
 "title": "Couchbase Buckets",
 "tags": [
  "couchbase",
  "data",
  "kv",
  "buckets",
  "scope",
  "collection"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": {
     "query": "label_values(kv_auth_cmds{cluster_name=~\"$cluster\"}, bucket)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kv_auth_cmds, cluster_name)"
    }
   },
   {
    "name": "scope",
    "label": "Scope",
    "query": {
     "query": "label_values(kv_collection_mem_used_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\"}, scope)"
    }
   },
   {
    "name": "collection",
    "label": "Collection",
    "query": {
     "query": "label_values(kv_collection_mem_used_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",scope=~\"$scope\"}, collection)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kv_auth_cmds{cluster_name=~\"$cluster\",bucket=~\"$bucket\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Buckets",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kv_curr_items{cluster_name=~\"$cluster\"}) by (bucket)",
     "legendFormat": "curr_items"
    },
    {
     "expr": "avg(kv_vb_perc_mem_resident_ratio{cluster_name=~\"$cluster\",state=~\"active|replica\"}) by (bucket)",
     "legendFormat": "resident_ratio"
    },
    {
     "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\"}[$__rate_interval])) by (bucket)",
     "legendFormat": "Ops"
    },
    {
     "expr": "sum(kv_mem_used_bytes{cluster_name=~\"$cluster\"}) by (bucket)",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "avg(kv_mem_used_bytes{cluster_name=~\"$cluster\"} / kv_ep_max_size{cluster_name=~\"$cluster\"}) by (bucket)",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "sum(\n    kv_ep_meta_data_memory_bytes{cluster_name=~\"$cluster\"} \n) by (bucket)",
     "legendFormat": "Metadata Memory"
    },
    {
     "expr": "avg(\n    kv_ep_meta_data_memory_bytes{cluster_name=~\"$cluster\"} \n    /\n    kv_ep_max_size{cluster_name=~\"$cluster\"}\n) by (bucket)",
     "legendFormat": "Metadata Utilization"
    },
    {
     "expr": "(\n   sum(kv_ep_meta_data_memory_bytes{cluster_name=~\"$cluster\"}) by (bucket) \n   -\n   sum(kv_curr_items_tot{cluster_name=~\"$cluster\"} * 58) by (bucket)\n)\n/ \nsum(kv_curr_items_tot{cluster_name=~\"$cluster\"}) by (bucket)",
     "legendFormat": "Avg. Key Size"
    },
    {
     "expr": "(\n    sum(kv_vb_itm_memory_uncompressed_bytes{cluster_name=~\"$cluster\"}) by (bucket)\n    - \n    sum(kv_ep_meta_data_memory_bytes{cluster_name=~\"$cluster\"}) by (bucket)\n)\n/ \n(\n    sum(kv_curr_items_tot{cluster_name=~\"$cluster\"}) by (bucket)\n    - \n    sum(kv_ep_num_non_resident{cluster_name=~\"$cluster\"}) by (bucket)\n)",
     "legendFormat": "Avg. Value Size"
    },
    {
     "expr": "sum(kv_num_vbuckets{cluster_name=~\"$cluster\",state=~\"active|replica\"}) by (bucket)\n/\n(\n    sum(kv_num_vbuckets{cluster_name=~\"$cluster\",state=~\"active|replica\"}) by (bucket)\n    -\n    (\n        sum(kv_num_vbuckets{cluster_name=~\"$cluster\",state=~\"active|replica\"}) by (bucket) \n        % \n        avg(kv_ep_max_vbuckets{cluster_name=~\"$cluster\"}) by (bucket)\n    )\n)",
     "legendFormat": "vBuckets Online"
    },
    {
     "expr": "count(count(kv_collection_mem_used_bytes{cluster_name=\"Demo Cluster 1\"}) by (bucket, scope)) by (bucket)",
     "legendFormat": "Scopes"
    },
    {
     "expr": "count(count(kv_collection_mem_used_bytes{cluster_name=\"Demo Cluster 1\"}) by (bucket, collection)) by (bucket)",
     "legendFormat": "Collections"
    }
   ]
  },
  {
   "title": "Compression Stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum without(instance, vbucket_state, datatype) (kv_datatype_count{cluster_name=~\"$cluster\",bucket=~\"$bucket\",datatype!~\"snappy.*\"})",
     "legendFormat": "Uncompressed Items"
    },
    {
     "expr": "sum without(instance, vbucket_state, datatype) (kv_datatype_count{cluster_name=~\"$cluster\",bucket=~\"$bucket\",datatype=~\"snappy.*\"})",
     "legendFormat": "Compressed Items"
    },
    {
     "expr": "sum without(instance, state) (kv_vb_itm_memory_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\"})",
     "legendFormat": "Compressed Memory"
    },
    {
     "expr": "sum without(instance, state) (kv_vb_itm_memory_uncompressed_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\"})",
     "legendFormat": "Uncompressed Memory"
    },
    {
     "expr": "1 - sum without(instance, state) (kv_vb_itm_memory_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\"})/ sum without(instance, state) (kv_vb_itm_memory_uncompressed_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\"})",
     "legendFormat": "Compression Ratio"
    }
   ]
  },
  {
   "title": "Scopes and Collections",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(kv_collection_data_size_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\"}) by (bucket, scope, collection)"
    },
    {
     "expr": "sum(kv_collection_item_count{cluster_name=~\"$cluster\",bucket=~\"$bucket\"}) by (bucket, scope, collection)"
    },
    {
     "expr": "sum(kv_collection_mem_used_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\"}) by (bucket, scope, collection)"
    },
    {
     "expr": "sum(rate(kv_collection_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"get\"}[$__rate_interval])) by (bucket, scope, collection)"
    },
    {
     "expr": "sum(rate(kv_collection_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"store\"}[$__rate_interval])) by (bucket, scope, collection)"
    },
    {
     "expr": "sum(rate(kv_collection_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",op=\"delete\"}[$__rate_interval])) by (bucket, scope, collection)"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Reads/sec Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by(le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"GET\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Writes/sec Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum by(le) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"SET\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Read - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum without (instance) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"GET\"}[$__rate_interval])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Read - 90th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum without (instance) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"GET\"}[$__rate_interval])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Read - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum without (instance) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"GET\"}[$__rate_interval])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Write - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum without (instance) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"SET\"}[$__rate_interval])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Write - 90th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum without (instance) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"SET\"}[$__rate_interval])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Write - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum without (instance) (rate(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=\"SET\"}[$__rate_interval])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Disk - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum without (instance, op) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Disk - 90th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum without (instance, op) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Disk - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum without (instance, op) (rate(kv_disk_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval])))",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Get Hits / sec",
     "type": "timeseries",
     "description": "Number of get operations per second to a bucket that resulted in a hit",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=\"get\",result=\"hit\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Get Misses / sec",
     "type": "timeseries",
     "description": "Number of get operations per second to a bucket that resulted in a miss",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=\"get\",result=\"miss\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Set Hits / sec",
     "type": "timeseries",
     "description": "Number of set (write) operations per second to a bucket",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=\"set\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "CAS Hits / sec",
     "type": "timeseries",
     "description": "Number of CAS operations per second to a bucket that resulted in a hit",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=\"cas\",result=\"hit\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "CAS Misses / sec",
     "type": "timeseries",
     "description": "Number of CAS operations per second to a bucket that resulted in a miss",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=\"cas\",result=\"miss\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "CAS Bad Value / sec",
     "type": "timeseries",
     "description": "Number of CAS operations per second to a bucket that resulted in a Bad Value",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=\"cas\",result=\"badval\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Delete Hits / sec",
     "type": "timeseries",
     "description": "Number of delete operations per second to a bucket that resulted in a hit",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=\"delete\",result=\"hit\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Delete Misses / sec",
     "type": "timeseries",
     "description": "Number of delete operations per second to a bucket that resulted in a miss",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=\"delete\",result=\"miss\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Locks / sec",
     "type": "timeseries",
     "description": "Number of lock operations per second to a bucket ",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=\"lock\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Increment Hits / sec",
     "type": "timeseries",
     "description": "Number of increment operations per second to a bucket that resulted in a hit",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=\"incr\",result=\"hit\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Increment Misses / sec",
     "type": "timeseries",
     "description": "Number of increment operations per second to a bucket that resulted in a miss",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=\"incr\",result=\"miss\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Flush / sec",
     "type": "timeseries",
     "description": "Number of flush operations per second to a bucket ",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=\"flush\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Decrement Hits / sec",
     "type": "timeseries",
     "description": "Number of decrement operations per second to a bucket that resulted in a hit",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=\"decr\",result=\"hit\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Decrement Misses / sec",
     "type": "timeseries",
     "description": "Number of decrement operations per second to a bucket that resulted in a miss",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=\"decr\",result=\"miss\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sub-Document Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SubDoc Mutation Inserted Bytes/sec",
     "type": "timeseries",
     "description": "The amount of mutation bytes inserted per second  through the sub-document api",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(kv_subdoc_mutation_inserted_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "SubDoc Mutation Updated Bytes/sec",
     "type": "timeseries",
     "description": "The amount of mutation bytes updated per second  through the sub-document api",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(kv_subdoc_mutation_updated_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "SubDoc Lookup Ops/sec",
     "type": "timeseries",
     "description": "The # of Lookup operations performed per second",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_subdoc_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=\"lookup\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "SubDoc Mutation Ops/sec",
     "type": "timeseries",
     "description": "The # of Mutation operations performed per second",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_subdoc_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=\"mutation\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "SubDoc Lookup Bytes Extracted/sec",
     "type": "timeseries",
     "description": "The amount of bytes extracted per second  through the sub-document api",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(kv_subdoc_lookup_extracted_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "SubDoc Lookup Bytes Searched/sec",
     "type": "timeseries",
     "description": "The amount of bytes searched per second  through the sub-document api",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(kv_subdoc_lookup_searched_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Current Items",
     "type": "timeseries",
     "description": "Number of unique items in this bucket - only active items, not replica",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kv_curr_items{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Current Items Total",
     "type": "timeseries",
     "description": "Number of unique items in this bucket - active + replica",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kv_curr_items_tot{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "IO Write Bytes / sec",
     "type": "timeseries",
     "description": "Number of bytes per second sent from this bucket",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ep_io_total_write_bytes_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Active Clock Drift",
     "type": "timeseries",
     "description": "Average drift (in seconds) per mutation on active vBuckets",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg(rate(kv_ep_hlc_drift_seconds{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",state=\"active\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Replica Clock Drift",
     "type": "timeseries",
     "description": "Average drift (in seconds) per mutation on replica vBuckets",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg(rate(kv_ep_hlc_drift_seconds{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",state=\"active\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "IO Read Bytes / sec / sec",
     "type": "timeseries",
     "description": "Number of bytes per second read from this bucket",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ep_io_total_read_bytes_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Background Wait TIme",
     "type": "timeseries",
     "description": "Background fetch time in microseconds",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(kv_bg_wait_seconds_sum{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Active Ahead Exceptions / sec",
     "type": "timeseries",
     "description": "Total number of ahead exceptions for all active vBuckets\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kv_ep_ahead_exceptions{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",state=\"active\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Replica Ahead Exceptions / sec",
     "type": "timeseries",
     "description": "Total number of ahead exceptions for all replica vBuckets\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kv_ep_ahead_exceptions{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",state=\"replica\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "CAS Drift Threshold Exceeded Ops / sec",
     "type": "timeseries",
     "description": "The number of HLC updates that had a value ahead of the local HLC and were over the   drift_ahead_threshold.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(increase(kv_ep_clock_cas_drift_threshold_exceeded{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "Total Memory Used",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(kv_mem_used_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Active vBucket Memory",
     "type": "timeseries",
     "description": "Amount of memory consumed by active vBuckets",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_itm_memory_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Replica vBucket Memory",
     "type": "timeseries",
     "description": "Amount of memory consumed by replica vBuckets",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_itm_memory_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Memory Overhead",
     "type": "timeseries",
     "description": "Extra memory used by transient data like persistence queues, replication queues, checkpoints, etc.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(kv_total_memory_overhead_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Active vBucket Metadata Memory",
     "type": "timeseries",
     "description": "Amount of memory being consumed for metadata for active vBuckets",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_meta_data_memory_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Replica vBucket Metadata Memory",
     "type": "timeseries",
     "description": "Amount of memory being consumed for metadata for replica vBuckets",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum without(instance) (kv_vb_meta_data_memory_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"replica\",instance=~\"$node\"})",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Temp OOMs",
     "type": "timeseries",
     "description": "Number of times temporary OOMs happened while processing operations.  Number of back-offs sent per second to client SDKs due to \"out of memory\" situations from this bucket.  ",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kv_ep_tmp_oom_errors{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Hard OOM Errors",
     "type": "timeseries",
     "description": "Number of times unrecoverable OOMs happened while processing operations.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kv_ep_oom_errors{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Non-Resident Items",
     "type": "timeseries",
     "description": "The number of non-resident items, both active and replica\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kv_vb_num_non_resident{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Ejections / sec",
     "type": "timeseries",
     "description": "Number of items per second evicted from this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ep_num_value_ejects{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Expiries / sec",
     "type": "timeseries",
     "description": "Number of items per second expired from this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum without(instance) (rate(kv_vb_expired{cluster_name=~\"$cluster\",bucket=~\"$bucket\",state=\"active\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Item Disk Fetches / sec",
     "type": "timeseries",
     "description": "Number of items fetched from disk.\n\nep_bg_meta_fetched - \nNumber of meta items fetched from disk.\n\nep_bg_remaining_jobs - \nNumber of remaining bg fetch jobs.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(\n    rate(kv_ep_bg_fetched{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])\n) by (bucket)",
       "legendFormat": "{{bucket}} - Items"
      }
     ]
    },
    {
     "title": "Meta Disk Fetches / sec",
     "type": "timeseries",
     "description": "Number of meta items fetched from disk.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(\n    rate(kv_ep_bg_meta_fetched{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])\n) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Remaining Disk Jobs ",
     "type": "timeseries",
     "description": "Number of remaining bg fetch jobs.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kv_ep_bg_remaining_jobs{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}\n) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Disk Queue items",
     "type": "timeseries",
     "description": "Number of Items in the Disk Queue",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kv_ep_diskqueue_items{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Disk Queue Fill Items / sec",
     "type": "timeseries",
     "description": "Items added to disk queue per second",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ep_diskqueue_fill{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (bucket) ",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Disk Queue Drain Items / sec",
     "type": "timeseries",
     "description": "Items drained from the disk queue per second",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ep_diskqueue_drain{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (bucket) ",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Disk Commit Time / sec",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ep_commit_time_seconds{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Disk Commits/sec",
     "type": "timeseries",
     "description": "Disk commits.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ep_commit_num{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Disk Write Failures / sec",
     "type": "timeseries",
     "description": "Number of disk write and read failures",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kv_ep_data_write_failed{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "DB Data Size",
     "type": "timeseries",
     "description": "Total size of valid data in db files",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(kv_ep_db_data_size_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "DB File Size",
     "type": "timeseries",
     "description": "Total size of the db files    ",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(kv_ep_db_file_size_bytes{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Disk Read Failures / sec",
     "type": "timeseries",
     "description": "Number of disk write and read failures (measured from ep_data_write_failed  and ep_data_read_failed)",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kv_ep_data_read_failed{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Flusher Todo",
     "type": "timeseries",
     "description": "Number of items currently being written.\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kv_ep_flusher_todo{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Flush Item Failures",
     "type": "timeseries",
     "description": "Number of times an item failed to flush due to storage errors.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kv_ep_item_flush_failed{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Commit Failures ",
     "type": "timeseries",
     "description": "Number of times a transaction failed to commit due to storage errors.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kv_ep_item_commit_failed{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "XDCR Incoming Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total XDCR Ops / sec",
     "type": "timeseries",
     "description": "Incoming XDCR operations per second for this bucket",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=~\"set_meta|get_meta|del_meta|set_ret_meta|del_ret_meta\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Set Metadata Ops / sec",
     "type": "timeseries",
     "description": "Number of set operations per second for this bucket as the target for XDCR\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=\"set_meta\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Delete Metadata Ops / sec",
     "type": "timeseries",
     "description": "Number of delete operations per second for this bucket as the target for XDCR\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=\"del_meta\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Get Metadata Ops / sec",
     "type": "timeseries",
     "description": "Number of metadata read operations per second for this bucket as the target for XDCR\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=\"get_meta\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "setRet Metadata Ops / sec\t\t",
     "type": "timeseries",
     "description": "Number of setRetMeta operations per second for this bucket as the target for XDCR\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=\"set_ret_meta\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "DelRet Metadata Ops / sec",
     "type": "timeseries",
     "description": "Number of delRetMeta operations per second for this bucket as the target for XDCR.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=\"del_ret_meta\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Get Metadata for Set Ops / sec",
     "type": "timeseries",
     "description": "Number of Get Metadata for Set operations per second for this bucket as the target for XDCR.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\",op=\"get_meta_for_set_meta\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  }
 ]
}