{
 "title": "Couchbase Cluster Overview",
 "tags": [
  "Couchbase",
  "Cluster",
  "Buckets",
  "Index",
  "Query",
  "Datacenter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kv_curr_items, cluster_name)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(cm_rest_request_enters_total{cluster_name=~\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes Up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(up{cluster_name=~\"$cluster\",job=~\".*couchbase.*|.*Couchbase.*\"}==1) by (instance))"
    }
   ]
  },
  {
   "title": "Nodes Down",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(up{cluster_name=~\"$cluster\",job=~\".*couchbase.*|.*Couchbase.*\"}==0) by (instance))"
    }
   ]
  },
  {
   "title": "Scrape Jobs Up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{cluster_name=~\"$cluster\"}==1)"
    }
   ]
  },
  {
   "title": "Scrape Jobs Down",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{cluster_name=~\"$cluster\"}==0)"
    }
   ]
  },
  {
   "title": "Couchbase Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(cm_rest_request_enters_total{cluster_name=~\"$cluster\"}) by (instance))\nor \nvector(0)",
     "legendFormat": "Total"
    },
    {
     "expr": "count(count(kv_curr_items{cluster_name=~\"$cluster\"}) by (instance))\nor \nvector(0)",
     "legendFormat": "Data"
    },
    {
     "expr": "count(count(index_memory_quota{cluster_name=~\"$cluster\"}) by (instance))\nor \nvector(0)",
     "legendFormat": "Index"
    },
    {
     "expr": "count(count(n1ql_requests{cluster_name=~\"$cluster\"}) by (instance))\nor \nvector(0)",
     "legendFormat": "Query"
    },
    {
     "expr": "count(count(fts_num_pindexes_actual{cluster_name=~\"$cluster\"}) by (instance))\nor \nvector(0)",
     "legendFormat": "FTS"
    },
    {
     "expr": "count(count(eventing_on_update_success{cluster_name=~\"$cluster\"}) by (instance))\nor \nvector(0)",
     "legendFormat": "Eventing"
    },
    {
     "expr": "count(count(cbas_disk_used_bytes_total{cluster_name=~\"$cluster\"}) by (instance))\nor \nvector(0)",
     "legendFormat": "Analytics"
    }
   ]
  },
  {
   "title": "Buckets",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(kv_curr_items{cluster_name=~\"$cluster\"}) by (bucket)",
     "legendFormat": "curr_items"
    },
    {
     "expr": "avg(kv_vb_perc_mem_resident_ratio{cluster_name=~\"$cluster\"}) by (bucket)",
     "legendFormat": "resident_ratio"
    },
    {
     "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\"}[$__rate_interval])) by (bucket)",
     "legendFormat": "Ops"
    },
    {
     "expr": "sum(kv_mem_used_bytes{cluster_name=~\"$cluster\"}) by (bucket)",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "avg(kv_mem_used_bytes{cluster_name=~\"$cluster\"} / kv_ep_max_size{cluster_name=~\"$cluster\"}) by (bucket)",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "sum(\n    kv_ep_meta_data_memory_bytes{cluster_name=~\"$cluster\"} \n) by (bucket)",
     "legendFormat": "Metadata Memory"
    },
    {
     "expr": "avg(\n    kv_ep_meta_data_memory_bytes{cluster_name=~\"$cluster\"} \n    /\n    kv_ep_max_size{cluster_name=~\"$cluster\"}\n) by (bucket)",
     "legendFormat": "Metadata Utilization"
    },
    {
     "expr": "(\n    (\n        sum(kv_mem_used_bytes{cluster_name=~\"$cluster\"}) by (bucket)\n        - \n        sum(kv_memory_used_bytes{cluster_name=~\"$cluster\",for=\"storedvalues\"}) by (bucket)\n    )\n    - \n    (\n        sum(kv_curr_items_tot{cluster_name=~\"$cluster\"} * 56) by (bucket)\n    )\n)\n/ \nsum(\n    kv_curr_items_tot{cluster_name=~\"$cluster\"}\n) by (bucket)",
     "legendFormat": "Avg. Key Size"
    },
    {
     "expr": "sum(\n    sum(kv_memory_used_bytes{cluster_name=~\"$cluster\",for=\"storedvalues\"}) by (bucket)\n) by (bucket)\n/ \n(\nsum(\n    kv_curr_items_tot{cluster_name=~\"$cluster\"} \n    - \n    kv_ep_num_non_resident{cluster_name=~\"$cluster\"}\n) by (bucket) + 1)",
     "legendFormat": "Avg. Value Size"
    },
    {
     "expr": "sum(kv_num_vbuckets{cluster_name=~\"$cluster\",state=~\"active|replica\"}) by (bucket)\n/\n(\n    sum(kv_num_vbuckets{cluster_name=~\"$cluster\",state=~\"active|replica\"}) by (bucket)\n    -\n    (\n        sum(kv_num_vbuckets{cluster_name=~\"$cluster\",state=~\"active|replica\"}) by (bucket) \n        % \n        avg(kv_ep_max_vbuckets{cluster_name=~\"$cluster\"}) by (bucket)\n    )\n)",
     "legendFormat": "vBuckets Online"
    },
    {
     "expr": "count(count(kv_collection_mem_used_bytes{cluster_name=\"$cluster\"}) by (bucket, scope)) by (bucket)",
     "legendFormat": "Scopes"
    },
    {
     "expr": "count(count(kv_collection_mem_used_bytes{cluster_name=\"$cluster\"}) by (bucket, collection)) by (bucket)",
     "legendFormat": "Collections"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime | $node",
     "type": "stat",
     "description": "Time since last boot",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
     "repeat": "node",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds{cluster_name=~\"$cluster\",instance=~\"$node\"} - node_boot_time_seconds{cluster_name=~\"$cluster\",instance=~\"$node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Processors",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
     "repeat": "node",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{cluster_name=~\"$cluster\",instance=~\"$node\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 7 },
     "repeat": "node",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "CPU Load",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 7 },
     "repeat": "node",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "1 - avg(irate(node_cpu_seconds_total{cluster_name=~\"$cluster\",mode=\"idle\",instance=~\"$node\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Memory Use",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 7 },
     "repeat": "node",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "1 - (node_memory_MemAvailable_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"} / node_memory_MemTotal_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Disk Used (Total)",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 7 },
     "repeat": "node",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(\n  (\n    node_filesystem_size_bytes{cluster_name=~\"$cluster\",instance=~\"$node\",mountpoint=~\".*/data|/\",fstype!=\"secfs2\"}\n    - \n    node_filesystem_avail_bytes{cluster_name=~\"$cluster\",instance=~\"$node\",mountpoint=~\".*/data|/\",fstype!=\"secfs2\"}\n  ) \n  / \n  node_filesystem_size_bytes{cluster_name=~\"$cluster\",instance=~\"$node\",mountpoint=~\".*/data|/\",fstype!=\"secfs2\"}\n)"
      }
     ]
    },
    {
     "title": "Network RX",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 7 },
     "repeat": "node",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Network TX",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 7 },
     "repeat": "node",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operations/sec",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",op!~\".*meta.*\"}[$__rate_interval])) by (op)",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "Current Items",
     "type": "timeseries",
     "description": "Number of unique items in this bucket - only active items, not replica",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kv_curr_items{cluster_name=~\"$cluster\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Resident Ratios",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg without(instance, state) (\n    kv_vb_perc_mem_resident_ratio{cluster_name=~\"$cluster\",state=~\"active|replica\"}\n)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Disk Queue Fill vs Drain Items/sec",
     "type": "timeseries",
     "description": "Items added to disk queue and drained from per second",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(kv_ep_diskqueue_fill{cluster_name=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Fill"
      },
      {
       "expr": "-sum(rate(kv_ep_diskqueue_drain{cluster_name=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Drain"
      }
     ]
    },
    {
     "title": "Item Disk Fetches/sec",
     "type": "timeseries",
     "description": "Number of items fetched from disk.\n\nep_bg_meta_fetched - \nNumber of meta items fetched from disk.\n\nep_bg_remaining_jobs - \nNumber of remaining bg fetch jobs.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(\n    rate(kv_ep_bg_fetched{cluster_name=~\"$cluster\"}[$__rate_interval])\n) by (bucket)",
       "legendFormat": "{{bucket}} - Items"
      }
     ]
    },
    {
     "title": "Disk/Commit Failures",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(kv_ep_data_write_failed{cluster_name=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Write Failures"
      },
      {
       "expr": "sum(increase(kv_ep_data_write_failed{cluster_name=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Read Failures"
      },
      {
       "expr": "sum(increase(kv_ep_item_commit_failed{cluster_name=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Commit Failures"
      }
     ]
    }
   ]
  },
  { "title": "N1QL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "N1QL Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(n1ql_load{cluster_name=~\"$cluster\"})",
     "legendFormat": "Results"
    }
   ]
  },
  {
   "title": "Average Request Time",
   "type": "stat",
   "description": "Average Execution Time (Overall), Average Service Time (time spent executing)",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(n1ql_request_time{cluster_name=~\"$cluster\"}[$__rate_interval]) / rate(n1ql_requests{cluster_name=~\"$cluster\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "N1QL Queries",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(n1ql_requests{cluster_name=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(n1ql_requests_250ms{cluster_name=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "> 250ms"
    },
    {
     "expr": "sum(rate(n1ql_requests_500ms{cluster_name=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "> 500ms"
    },
    {
     "expr": "sum(rate(n1ql_requests_1000ms{cluster_name=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "> 1000ms"
    },
    {
     "expr": "sum(rate(n1ql_requests_5000ms{cluster_name=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "> 5000ms"
    },
    {
     "expr": "sum(rate(n1ql_queued_requests{cluster_name=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "queued"
    },
    {
     "expr": "sum(rate(n1ql_prepared{cluster_name=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "prepared"
    }
   ]
  },
  {
   "title": "N1QL errors/warnings",
   "type": "timeseries",
   "description": "The number o N1QL errors, warnings, invalid requests and queued requests",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(n1ql_errors{cluster_name=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Errors"
    },
    {
     "expr": "sum(increase(n1ql_warnings{cluster_name=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Warnings"
    },
    {
     "expr": "sum(increase(n1ql_invalid_requests{cluster_name=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Invalid Requests"
    }
   ]
  },
  {
   "title": "Index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Index Distribution by Bucket",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(index_num_requests{cluster_name=~\"$cluster\"}) by (bucket)",
       "legendFormat": "Indexes"
      },
      {
       "expr": "sum(index_memory_used{cluster_name=~\"$cluster\"}) by (bucket)",
       "legendFormat": "Memory Used"
      },
      {
       "expr": "sum(index_items_count{cluster_name=~\"$cluster\"}) by (bucket)",
       "legendFormat": "Item Count"
      },
      {
       "expr": "avg(index_avg_scan_latency{cluster_name=~\"$cluster\"}>0) by (bucket)",
       "legendFormat": "Avg. Scan Latency"
      },
      {
       "expr": "avg(index_resident_percent{cluster_name=~\"$cluster\"} > 0) by (bucket)",
       "legendFormat": "Avg. Resident Ratio"
      },
      {
       "expr": "avg(rate(index_num_requests{cluster_name=~\"$cluster\"}[$__rate_interval])>0) by (bucket)",
       "legendFormat": "Avg. Scans / Sec"
      },
      {
       "expr": "avg(index_avg_item_size{cluster_name=~\"$cluster\"}>0) by (bucket)",
       "legendFormat": "Avg. Item Size"
      },
      {
       "expr": "count(index_avg_item_size{cluster_name=~\"$cluster\",index=~\".*primary*\"}>0) by (bucket)",
       "legendFormat": "Primary Indexes"
      },
      {
       "expr": "sum(index_data_size_on_disk{cluster_name=~\"$cluster\"}) by (bucket)",
       "legendFormat": "Size On Disk"
      }
     ]
    },
    {
     "title": "Index Distribution by Node",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(index_num_requests{cluster_name=~\"$cluster\"}) by (instance)",
       "legendFormat": "Indexes"
      },
      {
       "expr": "sum(index_memory_used{cluster_name=~\"$cluster\"}) by (instance)",
       "legendFormat": "Memory Used"
      },
      {
       "expr": "sum(index_items_count{cluster_name=~\"$cluster\"}) by (instance)",
       "legendFormat": "Item Count"
      },
      {
       "expr": "avg(index_avg_scan_latency{cluster_name=~\"$cluster\"}>0) by (instance)",
       "legendFormat": "Avg. Scan Latency"
      },
      {
       "expr": "avg(index_resident_percent{cluster_name=~\"$cluster\"} > 0) by (instance)",
       "legendFormat": "Avg. Resident Ratio"
      },
      {
       "expr": "avg(rate(index_num_requests{cluster_name=~\"$cluster\"}[$__rate_interval])>0) by (instance)",
       "legendFormat": "Avg. Scans / Sec"
      },
      {
       "expr": "avg(index_avg_item_size{cluster_name=~\"$cluster\"}>0) by (instance)",
       "legendFormat": "Avg. Item Size"
      },
      {
       "expr": "count(index_avg_item_size{cluster_name=~\"$cluster\",index=~\".*primary*\"}>0) by (instance)",
       "legendFormat": "Primary Indexes"
      },
      {
       "expr": "sum(index_data_size_on_disk{cluster_name=~\"$cluster\"}) by (instance)",
       "legendFormat": "Size On Disk"
      }
     ]
    }
   ]
  },
  {
   "title": "XDCR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "# of Replications",
     "type": "stat",
     "description": "Total # of replications in the cluster",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count by(targetClusterUUID,sourceBucketName,targetBucketName) ((xdcr_changes_left_total{cluster_name=~\"$cluster\",pipelineType=\"Main\"})))",
       "legendFormat": "{{replication}}"
      }
     ]
    },
    {
     "title": "Percent Complete",
     "type": "gauge",
     "description": "Percentage of checked items out of all checked and to-be-replicated items\n",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(\n    (xdcr_docs_processed_total{cluster_name=~\"$cluster\",pipelineType=\"Main\"} > 0 * 100) \n    / \n    (\n      xdcr_changes_left_total{cluster_name=~\"$cluster\",pipelineType=\"Main\"}  \n      + \n      xdcr_docs_processed_total{cluster_name=~\"$cluster\",pipelineType=\"Main\"} > 0\n    )\n)",
       "legendFormat": "{{replication}}"
      }
     ]
    },
    {
     "title": "Incoming XDCR Operations",
     "type": "stat",
     "description": "Incoming XDCR operations per second for this bucket",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kv_ops{cluster_name=~\"$cluster\",op=~\"del_meta|get_meta|set_meta\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Changes Left",
     "type": "stat",
     "description": "Number of mutations to be replicated to the remote cluster\n",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(xdcr_changes_left_total{cluster_name=~\"$cluster\",pipelineType=\"Main\"})"
      }
     ]
    },
    {
     "title": "Queue Size",
     "type": "stat",
     "description": "Amount of data being queued to be sent in an out nozzle.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(xdcr_size_rep_queue_bytes{cluster_name=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Data Replicated/sec",
     "type": "gauge",
     "description": "Bandwidth used during replication, measured in bytes per second.\n",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(xdcr_data_replicated_bytes{cluster_name=~\"$cluster\",pipelineType=\"Main\"}[$__rate_interval]))"
      }
     ]
    }
   ]
  }
 ]
}