{
 "title": "Couchbase Cluster Manager",
 "tags": [
  "Couchbase",
  "Data",
  "Buckets"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(cm_web_cache_hits_total, cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(cm_web_cache_hits_total{cluster_name=~\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Web", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Requests/sec by Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(cm_http_requests_total{cluster_name=~\"$cluster\",instance=~\"$node\",user!~\"-|@\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top 10 Request Paths",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(10, sum by (path) (rate(cm_http_requests_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "HTTP Requests/sec by User",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (user) (rate(cm_http_requests_total{cluster_name=~\"$cluster\",instance=~\"$node\",user!~\"-|@\"}[$__rate_interval]))",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Top 5 Request Users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5,sum by (user) (rate(cm_http_requests_total{cluster_name=~\"$cluster\",instance=~\"$node\",user!~\"-|@\"}[$__rate_interval])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "HTTP Requests/sec by Type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(cm_http_requests_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP Requests/sec by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(cm_http_requests_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Web Cache Hits/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(cm_web_cache_hits_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Web Cache Updates Hits/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(cm_web_cache_updates_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Web Cache Inner Hits/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(cm_web_cache_inner_hits_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hibernate Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(cm_request_hibernates_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "Hibernate - {{instance}}"
    },
    {
     "expr": "rate(cm_request_unhibernates_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "Unhibernate - {{instance}}"
    }
   ]
  },
  {
   "title": "Node Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Processes",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sysproc_cpu_utilization{cluster_name=\"$cluster\",instance=~\"$node\"}"
      },
      {
       "expr": "sysproc_mem_size{cluster_name=\"$cluster\",instance=~\"$node\"}"
      },
      {
       "expr": "sysproc_mem_resident{cluster_name=\"$cluster\",instance=~\"$node\"}"
      },
      {
       "expr": "sysproc_mem_share{cluster_name=\"$cluster\",instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "CPU Utilization ",
     "type": "timeseries",
     "description": "CPU Utilization per Node.\n\nRequires Node Exporter Metrics (https://github.com/prometheus/node_exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (\n avg(\n    rate(\n      node_cpu_seconds_total{cluster_name=~\"$cluster\",instance=~\"$node\",mode=\"idle\"}[$__rate_interval]\n    )\n  ) by (instance)\n  * 100\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Cluster Manager CPU Usage",
     "type": "timeseries",
     "description": "CPU Utilization for cbq-engine process per Node.\n\nRequires Process Exporter (https://github.com/ncabatoff/process-exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(\n    rate(\n      namedprocess_namegroup_cpu_seconds_total{instance=~\"$node\",groupname=~\"(ns_server|goport|gosecrets|godu|saslauthd-port|beam-smp|portsigar).*\",mode=~\"user|system\"}[$__rate_interval]\n    ) \n) by (instance, groupname)",
       "legendFormat": "{{groupname}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Memory Utilization ",
     "type": "timeseries",
     "description": "Memory Utilization  per Node.\n\nRequires Node Exporter Metrics (https://github.com/prometheus/node_exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * (\n  1 \n  - \n  (\n    avg(\n      avg_over_time(\n        node_memory_MemFree_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]\n      ) + \n      avg_over_time(\n        node_memory_Cached_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]\n      ) + \n      avg_over_time(\n        node_memory_Buffers_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]\n      )\n    ) by (instance)\n  )\n  / \n  avg(node_memory_MemTotal_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  ) by (instance)\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Cluster Manager Memory Usage",
     "type": "timeseries",
     "description": "Memory Usage for cbq-engine process per Node.\n\nRequires Process Exporter (https://github.com/ncabatoff/process-exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(\n  avg_over_time(namedprocess_namegroup_memory_bytes{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"(ns_server|goport|gosecrets|godu|saslauthd-port|beam-smp|portsigar).*\",memtype=\"swapped\"}[$__rate_interval])\n  + \n  ignoring (memtype) avg_over_time(namedprocess_namegroup_memory_bytes{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"(ns_server|goport|gosecrets|godu|saslauthd-port|beam-smp|portsigar).*\",memtype=\"resident\"}[$__rate_interval])\n) by (groupname, instance)",
       "legendFormat": "{{groupname}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Disk Operations",
     "type": "timeseries",
     "description": "The number of bytes read from or written to the device per second.\nRequires Node Exporter Metrics (https://github.com/prometheus/node_exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_written_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Write bytes - {{instance}}"
      },
      {
       "expr": "-sum(rate(node_disk_read_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Read bytes - {{instance}}"
      }
     ]
    },
    {
     "title": "Cluster Manager Disk Operations",
     "type": "timeseries",
     "description": "Disk Operations for cbq-engine process per Node. \n\nRequires Process Exporter (https://github.com/ncabatoff/process-exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(namedprocess_namegroup_write_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"(ns_server|goport|gosecrets|godu|saslauthd-port|beam-smp|portsigar).*\"}[$__rate_interval])) by (groupname, instance)",
       "legendFormat": "{{groupname}} - write - {{instance}}"
      },
      {
       "expr": "-sum(rate(namedprocess_namegroup_read_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"(ns_server|goport|gosecrets|godu|saslauthd-port|beam-smp|portsigar).*\"}[$__rate_interval])) by (groupname, instance)",
       "legendFormat": "{{groupname}} - read - {{instance}}"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "Basic network info per interface.\nRequires Node Exporter Metrics (https://github.com/prometheus/node_exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "-sum(rate(node_network_receive_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])*8) by (instance)",
       "legendFormat": "{{instance}} - RX"
      },
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])*8) by (instance)",
       "legendFormat": "{{instance}} - TX"
      }
     ]
    },
    {
     "title": "Cluster Manager Open File Descriptors",
     "type": "timeseries",
     "description": "The # of Open File Descriptors for the cbq-engine process. \n\nRequires Process Exporter (https://github.com/ncabatoff/process-exporter)\n",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(\n  max_over_time(namedprocess_namegroup_open_filedesc{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"(ns_server|goport|gosecrets|godu|saslauthd-port|beam-smp|portsigar).*\"}[$__rate_interval])\n) by (groupname, instance)",
       "legendFormat": "{{groupname}} - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Requests Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum by(le) (rate(cm_http_requests_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "HTTP Requests - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, rate(cm_http_requests_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "HTTP Requests - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(cm_http_requests_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Status Latency Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "sum by(le) (rate(cm_status_latency_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Status Latency - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, rate(cm_status_latency_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Status Latency - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(cm_status_latency_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Timer Lag Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum by(le) (rate(cm_timer_lag_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Timer Lag - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, rate(cm_timer_lag_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Timer Lag - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(cm_timer_lag_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Outgoing Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outgoing HTTP Requests (XDCR)/sec Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum by(le) (rate(cm_outgoing_http_requests_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\",type=\"goxdcr\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Outgoing HTTP Requests (XDCR)/sec - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, rate(cm_outgoing_http_requests_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\",type=\"goxdcr\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Outgoing HTTP Requests (XDCR)/sec - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(cm_outgoing_http_requests_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\",type=\"goxdcr\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Outgoing HTTP Requests (Indexer)/sec Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum by(le) (rate(cm_outgoing_http_requests_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\",type=\"indexer\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Outgoing HTTP Requests (Indexer)/sec - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, rate(cm_outgoing_http_requests_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\",type=\"indexer\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Outgoing HTTP Requests (Indexer)/sec - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(cm_outgoing_http_requests_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\",type=\"indexer\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Outgoing HTTP Requests (Eventing)/sec Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "sum by(le) (rate(cm_outgoing_http_requests_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\",type=\"eventing\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Outgoing HTTP Requests (Eventing)/sec - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, rate(cm_outgoing_http_requests_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\",type=\"eventing\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Outgoing HTTP Requests (Eventing)/sec - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(cm_outgoing_http_requests_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\",type=\"eventing\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Outgoing HTTP Requests (Prometheus)/sec Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "sum by(le) (rate(cm_outgoing_http_requests_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\",type=\"prometheus\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Outgoing HTTP Requests (Prometheus)/sec - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, rate(cm_outgoing_http_requests_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\",type=\"prometheus\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Outgoing HTTP Requests (Prometheus)/sec - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(cm_outgoing_http_requests_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\",type=\"prometheus\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Outgoing HTTP Requests (FTS)/sec Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "sum by(le) (rate(cm_outgoing_http_requests_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\",type=\"fts\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Outgoing HTTP Requests (FTS)/sec - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, rate(cm_outgoing_http_requests_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\",type=\"fts\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Outgoing HTTP Requests (FTS)/sec - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(cm_outgoing_http_requests_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\",type=\"fts\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memcached Call Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memcached Call Time Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum by(le) (rate(cm_memcached_call_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Memcached Call Times - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, avg by(bucket, le) (rate(cm_memcached_call_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memcached Call Times - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg by(bucket, le) (rate(cm_memcached_call_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memcached Q Call Times Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum by(le) (rate(cm_memcached_q_call_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Memcached Q Call Times - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, avg by(bucket, le) (rate(cm_memcached_q_call_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memcached Q Call Times - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg by(bucket, le) (rate(cm_memcached_q_call_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memcached E2E Call Times Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "sum by(le) (rate(cm_memcached_e2e_call_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Memcached E2E Call Times - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, avg by(bucket, le) (rate(cm_memcached_e2e_call_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memcached E2E Call Times - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg by(bucket, le) (rate(cm_memcached_e2e_call_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Chronicle Disk Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chronicle Disk Latency (append) Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 78 },
     "targets": [
      {
       "expr": "sum by(le) (cm_chronicle_disk_latency_seconds_bucket{cluster_name=~\"$cluster\",op=\"append\",instance=~\"$node\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Chronicle Disk Latency (append) - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, cm_chronicle_disk_latency_seconds_bucket{cluster_name=~\"$cluster\",op=\"append\",instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Chronicle Disk Latency (append) - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(cm_chronicle_disk_latency_seconds_bucket{cluster_name=~\"$cluster\",op=\"append\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Chronicle Disk Latency (prepare_snapshot)/sec Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "sum by(le) (cm_chronicle_disk_latency_seconds_bucket{cluster_name=~\"$cluster\",op=\"prepare_snapshot\",instance=~\"$node\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Chronicle Disk Latency (prepare_snapshot) - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, cm_chronicle_disk_latency_seconds_bucket{cluster_name=~\"$cluster\",op=\"prepare_snapshot\",instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Chronicle Disk Latency (prepare_snapshot) - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(cm_chronicle_disk_latency_seconds_bucket{cluster_name=~\"$cluster\",op=\"prepare_snapshot\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Chronicle Disk Latency (sync)/sec Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "sum by(le) (cm_chronicle_disk_latency_seconds_bucket{cluster_name=~\"$cluster\",op=\"sync\",instance=~\"$node\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Chronicle Disk Latency (sync) - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, cm_chronicle_disk_latency_seconds_bucket{cluster_name=~\"$cluster\",op=\"sync\",instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Chronicle Disk Latency (sync) - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(cm_chronicle_disk_latency_seconds_bucket{cluster_name=~\"$cluster\",op=\"sync\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Chronicle Disk Latency (delete) Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 96 },
     "targets": [
      {
       "expr": "sum by(le) (cm_chronicle_disk_latency_seconds_bucket{cluster_name=~\"$cluster\",op=\"delete\",instance=~\"$node\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Chronicle Disk Latency (delete) - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, cm_chronicle_disk_latency_seconds_bucket{cluster_name=~\"$cluster\",op=\"delete\",instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Chronicle Disk Latency (delete) - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, cm_chronicle_disk_latency_seconds_bucket{cluster_name=~\"$cluster\",op=\"delete\",instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Chronicle Disk Latency (delete_snapshot)/sec Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 102 },
     "targets": [
      {
       "expr": "sum by(le) (cm_chronicle_disk_latency_seconds_bucket{cluster_name=~\"$cluster\",op=\"delete_snapshot\",instance=~\"$node\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Chronicle Disk Latency (delete_snapshot) - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, cm_chronicle_disk_latency_seconds_bucket{cluster_name=~\"$cluster\",op=\"delete_snapshot\",instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Chronicle Disk Latency (delete_snapshot) - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, cm_chronicle_disk_latency_seconds_bucket{cluster_name=~\"$cluster\",op=\"delete_snapshot\",instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MRU Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "MRU Cache Lookup Time  Rate Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "sum by(le) (rate(cm_mru_cache_lookup_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "MRU Cache Lookup Time Rate - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, rate(cm_mru_cache_lookup_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MRU Cache Lookup Time  Rate- 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(cm_mru_cache_lookup_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MRU Cache Lock Time (item)  Rate Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "sum by(le) (rate(cm_mru_cache_lock_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\",type=\"item\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "MRU Cache Lock Time (Item) Rate - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, rate(cm_mru_cache_lock_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\",type=\"item\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MRU Cache Lock Time (Item)  Rate - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(cm_mru_cache_lock_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\",type=\"item\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MRU Cache Lock Time (Housekeeping) Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "sum by(le) (cm_mru_cache_lock_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\",type=\"housekeeping\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "MRU Cache Lock Time (Housekeeping) - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, cm_mru_cache_lock_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\",type=\"housekeeping\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MRU Cache Lock Time (item) - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, cm_mru_cache_lock_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\",type=\"housekeeping\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MRU Cache Add Time Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 97 },
     "targets": [
      {
       "expr": "sum by(le) (cm_mru_cache_add_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "MRU Cache Add Time - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, cm_mru_cache_add_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MRU Cache Add Time - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, cm_mru_cache_add_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MRU Cache Flush Time Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 103 },
     "targets": [
      {
       "expr": "sum by(le) (cm_mru_cache_flush_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "MRU Cache Flush Time - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, cm_mru_cache_flush_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MRU Cache Flush Time - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(cm_mru_cache_flush_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Leases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lease Acquirer Inflight Time Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "sum by(le) (rate(cm_lease_aquirer_time_inflight_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Lease Acquirer Inflight Time - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, rate(cm_lease_aquirer_time_inflight_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Lease Acquirer Inflight Time - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(cm_lease_aquirer_time_inflight_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Lease Acquirer Start Time - Estimate Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum by(le) (rate(cm_lease_aquirer_start_time_minus_prev_acquire_estimate_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Lease Acquirer Start Time - Estimate - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, rate(cm_lease_aquirer_start_time_minus_prev_acquire_estimate_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Lease Acquirer Start Time - Estimate - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(cm_lease_aquirer_start_time_minus_prev_acquire_estimate_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Lease Acquirer Estimate - Start Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sum by(le) (rate(cm_lease_aquirer_prev_acquire_estimate_minus_start_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Lease Acquirer Estimate - Start - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, rate(cm_lease_aquirer_prev_acquire_estimate_minus_start_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Lease Acquirer Estimate - Start - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(cm_lease_aquirer_prev_acquire_estimate_minus_start_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NS Config",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "NS Config Merger Runtime Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum by(le) (cm_ns_config_merger_run_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "NS Config Merger Runtime - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, cm_ns_config_merger_run_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "NS Config Merger Runtime - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, cm_ns_config_merger_run_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "NS Config Merger Sleep Time Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sum by(le) (cm_ns_config_merger_sleep_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "NS Config Merger Sleep Time - 50th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, cm_ns_config_merger_sleep_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "NS Config Merger Sleep Time - 99th Percentile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, cm_ns_config_merger_sleep_time_seconds_bucket{cluster_name=~\"$cluster\",instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}