{
 "title": "Couchbase Logs - Data Service Overview",
 "description": "A Dashboard for an Overview of the Couchbase Data Service Logs",
 "tags": [
  "couchbase",
  "logs",
  "data",
  "kv",
  "loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({file=\"slow_query.log\"}, couchbase_cluster_name)"
   },
   {
    "name": "level",
    "label": "Level",
    "query": "label_values({couchbase_cluster_name=\"$cluster\",file=~\"memcached.log\"}, level)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values({couchbase_cluster_name=\"$cluster\",file=\"memcached.log\",level=~\"$level\"}, couchbase_node)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages by Log Level/sec",
   "type": "timeseries",
   "description": "The number of log messages per second, by log level",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (level) (\n  rate(\n    {couchbase_cluster_name=\"$cluster\", file=\"memcached.log\", level=~\"$level\",couchbase_node=~\"$node\"} [$interval]\n  )\n)",
     "legendFormat": "{{level}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "Total Messages by Log Level",
   "type": "piechart",
   "description": "The number of log messages by level in the range",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (level) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"memcached.log\", level=~\"$level\",couchbase_node=~\"$node\"} [$__range]\n  )\n)",
     "legendFormat": "{{level}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "Warnings Messages",
   "type": "timeseries",
   "description": "Warning Messages by Type",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (message_type) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\",file=\"memcached.log\",couchbase_node=~\"$node\",level=\"WARN\"} \n    | json  \n    | label_format message_type=`{{ regexReplaceAll \"^(\\\\d+\\\\s+)|\\\\([^)]+\\\\)\\\\s*|[0-9]+:\\\\s*|(\\\\.\\\\s+)?(\\\\{).+$|on vb:[0-9]+|on thread.+$|\\\\s+for\\\\s.+$|,.+|\\\\s+\\\\[.+$\" .message \"\" }}` \n    | __error__=\"\" [$interval]\n  )\n)",
     "legendFormat": "{{client_ip}}",
     "resolution": 5
    }
   ]
  },
  { "title": "HELOs / Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "HELOs by Client IP",
   "type": "timeseries",
   "description": "Count of HELOs / Bootstrap Requests ",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (client_ip) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\",file=\"memcached.log\",couchbase_node=~\"$node\",level=~\"$level\"}  \n    |= \"HELO\"\n    | json  \n    | __error__=\"\" [$interval]\n  )\n)",
     "legendFormat": "{{client_ip}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "HELOs by Client",
   "type": "timeseries",
   "description": "Count of HELOs / Bootstrap Requests ",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (client_sdk) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\",file=\"memcached.log\",couchbase_node=~\"$node\",level=~\"$level\"} \n    |= \"HELO\"\n    | json  \n    | __error__=\"\" [$interval]\n  )\n)",
     "legendFormat": "{{client_sdk}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "Total HELOs by Client IP",
   "type": "table",
   "description": "Count of HELOs / Bootstrap Requests ",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (client_ip) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\",file=\"memcached.log\",couchbase_node=~\"$node\",level=~\"$level\"} \n    |= \"HELO\"\n    | json \n    | __error__=\"\" [$__range]\n  )\n)",
     "legendFormat": "{{client_ip}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "Total HELOs by Client",
   "type": "table",
   "description": "Count of HELOs / Bootstrap Requests ",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (client_sdk) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\",file=\"memcached.log\",couchbase_node=~\"$node\",level=~\"$level\"} \n    |= \"HELO\"\n    | json  \n    | __error__=\"\" [$__range]\n  )\n)",
     "legendFormat": "{{ client_sdk }}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "Slow Runtime Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slow Runtime Messages by Bucket",
     "type": "timeseries",
     "description": "Slow Runtime Messages by Bucket",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (bucket) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\",file=\"memcached.log\",couchbase_node=~\"$node\"} [$interval]\n    |= \"Slow runtime\"\n  )\n)",
       "legendFormat": "{{client_ip}}",
       "resolution": 5
      }
     ]
    },
    {
     "title": "Slow Runtime Messages by Type",
     "type": "timeseries",
     "description": "Slow Runtime Messages by Type",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (message_type) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\",file=\"memcached.log\",couchbase_node=~\"$node\"} \n    |= \"Slow runtime\" \n    | json      \n    | label_format message_type=`{{ regexReplaceAll \"^.+'([^.']+)\\\\.?'.+\" .message \"${1}\" }}`    \n    | label_format message_type=`{{ regexReplaceAll \"on\\\\s+vb:.+\" .message_type \"\" }}` \n    | __error__=\"\" [$interval]\n  )\n)",
       "legendFormat": "{{client_ip}}",
       "resolution": 5
      }
     ]
    },
    {
     "title": "Slow Runtime Messages",
     "type": "table",
     "description": "Slow Runtime Messages by Type",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (message_type) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\",file=\"memcached.log\",couchbase_node=~\"$node\"} \n    |= \"Slow runtime\" \n    | json      \n    | label_format message_type=`{{ regexReplaceAll \"^.+'([^.']+)\\\\.?'.+\" .message \"${1}\" }}`    \n    | label_format message_type=`{{ regexReplaceAll \"on\\\\s+vb:.+\" .message_type \"\" }}` \n    | __error__=\"\" [$__range]\n  )\n)",
       "legendFormat": "{{ message_type }}",
       "resolution": 5
      }
     ]
    }
   ]
  },
  {
   "title": "Slow Operation Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slow Operation Messages by Bucket",
     "type": "timeseries",
     "description": "Slow Operation Messages by Bucket",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (bucket) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\",file=\"memcached.log\",couchbase_node=~\"$node\"}  [$interval]\n    |= \"Slow operation\" \n  )\n)",
       "legendFormat": "{{client_ip}}",
       "resolution": 5
      }
     ]
    },
    {
     "title": "Slow Operation Messages by Type",
     "type": "timeseries",
     "description": "Slow Operation Messages by Type",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (message_type) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\",file=\"memcached.log\",couchbase_node=~\"$node\"} \n    |= \"Slow operation\" \n    | json      \n    | label_format message_type=`{{ regexReplaceAll \"^.+\\\"command\\\":\\\"([^\\\"]+)\\\".+$\" .message \"${1}\" }}` \n    | __error__=\"\" [$interval]\n  )\n)",
       "legendFormat": "{{client_ip}}",
       "resolution": 5
      }
     ]
    },
    {
     "title": "Slow Operation Messages",
     "type": "table",
     "description": "Slow Operation Messages by Type",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (message_type) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\",file=\"memcached.log\",couchbase_node=~\"$node\"} \n    |= \"Slow operation\" \n    | json      \n    | label_format message_type=`{{ regexReplaceAll \"^.+\\\"command\\\":\\\"([^\\\"]+)\\\".+$\" .message \"${1}\" }}` \n    | __error__=\"\" [$__range]\n  )\n)",
       "legendFormat": "{{ message_type }}",
       "resolution": 5
      }
     ]
    }
   ]
  },
  {
   "title": "Slow Scheduling Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slow Scheduling Messages by Bucket",
     "type": "timeseries",
     "description": "Slow Scheduling Messages by Bucket",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (bucket) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\",file=\"memcached.log\",couchbase_node=~\"$node\"} [$interval]\n    |= \"Slow scheduling\" \n  )\n)",
       "legendFormat": "{{client_ip}}",
       "resolution": 5
      }
     ]
    },
    {
     "title": "Slow Scheduling Messages by Type",
     "type": "timeseries",
     "description": "Slow Runtime Messages by Type",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (message_type) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\",file=\"memcached.log\",couchbase_node=~\"$node\"} \n    |= \"Slow scheduling\" \n    | json      \n    | label_format message_type=`{{ regexReplaceAll \"^[^']+'([^']+)'.+$\" .message \"${1}\" }}`    \n    | __error__=\"\" [$interval]\n  )\n)",
       "legendFormat": "{{client_ip}}",
       "resolution": 5
      }
     ]
    },
    {
     "title": "Slow Scheduling Messages",
     "type": "table",
     "description": "Slow Scheduling Messages by Type",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (message_type) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\",file=\"memcached.log\",couchbase_node=~\"$node\"} \n    |= \"Slow scheduling\" \n    | json      \n    | label_format message_type=`{{ regexReplaceAll \"^[^']+'([^']+)'.+$\" .message \"${1}\" }}`    \n    | __error__=\"\" [$__range]\n  )\n)",
       "legendFormat": "{{ message_type }}",
       "resolution": 5
      }
     ]
    }
   ]
  }
 ]
}