{
 "title": "Couchbase // Connector // Elasticsearch",
 "description": "Couchbase Elasticsearch Connector Dashboard Overview ",
 "tags": [
  "couchbase",
  "elasticsearch",
  "connector",
  "dcp",
  "cbes"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(dcp_client_request_total, cluster_name)"
    }
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": {
     "query": "label_values(dcp_server_request_total{cluster_name=\"$cluster\"},bucket)"
    }
   },
   {
    "name": "opcode",
    "query": {
     "query": "label_values(dcp_server_request_total{cluster_name=\"$cluster\",bucket=~\"$bucket\"},opcode)"
    }
   },
   {
    "name": "remote",
    "query": {
     "query": "label_values(dcp_connection_status{cluster_name=\"$cluster\",bucket=~\"$bucket\"}, remote)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Connector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Estimated Backlog",
   "type": "timeseries",
   "description": "Estimated Couchbase changes yet to be processed by this node.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(cbes_backlog{cluster_name=\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connector Data Written/sec",
   "type": "timeseries",
   "description": "An estimate of the number of bytes the connector has written to Elasticsearch.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(cbes_throughput_bytes_total{cluster_name=\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connector Write Queue",
   "type": "timeseries",
   "description": "Document events currently buffered in memory.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cbes_write_queue{cluster_name=\"$cluster\",bucket=~\"$bucket\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Elasticsearch Wait Seconds",
   "type": "stat",
   "description": "Duration of in-flight Elasticsearch bulk request (including any retries). Long duration may indicate connector has stalled.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cbes_es_wait_seconds{cluster_name=\"$cluster\",bucket=~\"$bucket\"}"
    }
   ]
  },
  {
   "title": "Docs Rejected",
   "type": "stat",
   "description": "Permanent indexing failure; usually result in an entry being added to the rejection log Elasticsearch index.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(cbes_doc_rejected_total{cluster_name=\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Checkpoint Save Failures",
   "type": "stat",
   "description": "Failed to save a replication checkpoint document to Couchbase.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(cbes_save_state_fail_total{cluster_name=\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Individual Doc Retries Due to Failure",
   "type": "stat",
   "description": "Failure to write an individual document. (For each `bulkRetry` event, one or more `docWriteRetry` events are recorded, indicating how many failures there were in the bulk request.)",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(cbes_doc_write_retry_total{cluster_name=\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Elasticsearch Failed Connections",
   "type": "stat",
   "description": "Failed Elasticsearch connection attempts.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(cbes_es_conn_fail_total{cluster_name=\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Rejection Log Failures",
   "type": "stat",
   "description": "Failure to add a record to the rejection log Elasticsearch index.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(cbes_rejection_log_fail_total{cluster_name=\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Bulk Retries Due to Failure",
   "type": "stat",
   "description": "Elasticsearch bulk request retry due to a temporary failure.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(cbes_bulk_retry_total{cluster_name=\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Max per Doc Index Latency",
   "type": "stat",
   "description": "Duration of an Elasticsearch bulk request (including retries), divided by the number of items in the bulk request.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cbes_bulk_index_per_doc_seconds_max{cluster_name=\"$cluster\",bucket=~\"$bucket\"}"
    }
   ]
  },
  {
   "title": "Connector Avg. Latency",
   "type": "stat",
   "description": "The time between when the connector is notified of a database change and when the change is written to Elasticsearch.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cbes_latency_seconds_sum{cluster_name=\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval])\n/\nrate(cbes_latency_seconds_count{cluster_name=\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Elasticsearch Indexing Retry Delay",
   "type": "stat",
   "description": "Time spent waiting after a temporary indexing failure before the request is retried.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cbes_retry_delay_seconds_max{cluster_name=\"$cluster\",bucket=~\"$bucket\"}"
    }
   ]
  },
  {
   "title": "Preparing Index Request Latency",
   "type": "stat",
   "description": "Time spent preparing an Elasticsearch indexing request.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cbes_new_index_req_seconds_max{cluster_name=\"$cluster\",bucket=~\"$bucket\"}"
    }
   ]
  },
  {
   "title": "Remotes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Remote Node",
     "type": "text",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
     "repeat": "remote",
     "options": { "content": "<br><br><h3>${remote}</h3>" },
     "targets": [
      {
       "expr": "increase(dcp_disconnect_total{cluster_name=\"$cluster\",bucket=~\"$bucket\",remote=~\"$remote\"}[$__rate_interval])",
       "legendFormat": "{{remote}}"
      }
     ]
    },
    {
     "title": "DCP Connection Status",
     "type": "stat",
     "description": "The status of the DCP Connection for the Remote",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 20 },
     "repeat": "remote",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dcp_connection_status{cluster_name=\"$cluster\",bucket=~\"$bucket\",remote=~\"$remote\"}",
       "legendFormat": "{{remote}}"
      }
     ]
    },
    {
     "title": "DCP Bytes Read/sec",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 20 },
     "repeat": "remote",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(dcp_bytes_read_total{cluster_name=\"$cluster\",bucket=~\"$bucket\",remote=~\"$remote\"}[$__rate_interval])",
       "legendFormat": "{{remote}}"
      }
     ]
    },
    {
     "title": "DCP Connects",
     "type": "stat",
     "description": "The total number of DCP connects",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 20 },
     "repeat": "remote",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(dcp_connect_total{cluster_name=\"$cluster\",bucket=~\"$bucket\",remote=~\"$remote\",result=\"success\"}[$__rate_interval])",
       "legendFormat": "{{remote}}"
      }
     ]
    },
    {
     "title": "DCP Disconnects",
     "type": "stat",
     "description": "The total number of DCP disconnects",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 20 },
     "repeat": "remote",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(dcp_disconnect_total{cluster_name=\"$cluster\",bucket=~\"$bucket\",remote=~\"$remote\"}[$__rate_interval])",
       "legendFormat": "{{remote}}"
      }
     ]
    },
    {
     "title": "DCP Client Requests",
     "type": "timeseries",
     "description": "The total # of client DCP requests for various operations",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
     "repeat": "remote",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(dcp_client_request_total{cluster_name=\"$cluster\",bucket=~\"$bucket\",remote=~\"$remote\"}[$__rate_interval])",
       "legendFormat": "{{opcode}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "DCP Scheduled Pooling Tasks",
     "type": "stat",
     "description": "The number of DCP pooling tasks",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dcp_scheduled_polling_tasks{cluster_name=\"$cluster\",bucket=~\"$bucket\"}"
      }
     ]
    },
    {
     "title": "DCP Reconfigures",
     "type": "stat",
     "description": "The amount of times that DCP connections have been reconfigured",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(dcp_reconfigure_total{cluster_name=\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "DCP Remove Channel Events",
     "type": "timeseries",
     "description": "The total number of DCP remove channel events",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(dcp_remove_channel_total{cluster_name=\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DCP Add Channel",
     "type": "timeseries",
     "description": "The total number of DCP add channel events",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(dcp_add_channel_total{cluster_name=\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DCP Server Requests - $opcode",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
     "repeat": "opcode",
     "targets": [
      {
       "expr": "increase(dcp_server_request_total{cluster_name=\"$cluster\",bucket=~\"$bucket\",opcode=\"$opcode\"}[$__rate_interval])",
       "legendFormat": "{{ remote }}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Buffers and Classes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Loaded Classes",
     "type": "stat",
     "description": "The number of classes that are currently loaded in the Java virtual machine",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{cluster_name=\"$cluster\",bucket=~\"$bucket\"}"
      }
     ]
    },
    {
     "title": "JVM Unloaded Classes",
     "type": "stat",
     "description": "The total number of classes unloaded since the Java virtual machine has started execution",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(jvm_classes_unloaded_classes_total{cluster_name=\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "JVM Buffer Count",
     "type": "stat",
     "description": "An estimate of the number of buffers in the pool",
     "gridPos": { "h": 6, "w": 10, "x": 6, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{cluster_name=\"$cluster\",bucket=~\"$bucket\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "JVM Buffer Memory Used",
     "type": "timeseries",
     "description": "An estimate of the memory that the Java virtual machine is using for this buffer pool",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{cluster_name=\"$cluster\",bucket=~\"$bucket\"}",
       "legendFormat": "{{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Daemon Threads",
     "type": "stat",
     "description": "The current number of live daemon threads",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_threads_daemon_threads{cluster_name=\"$cluster\",bucket=~\"$bucket\"}"
      }
     ]
    },
    {
     "title": "JVM Peak Threads",
     "type": "stat",
     "description": "The peak live thread count since the Java virtual machine started or peak was reset",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_threads_peak_threads{cluster_name=\"$cluster\",bucket=~\"$bucket\"}"
      }
     ]
    },
    {
     "title": "JVM Live Threads",
     "type": "stat",
     "description": "The current number of live threads including both daemon and non-daemon threads",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_threads_live_threads{cluster_name=\"$cluster\",bucket=~\"$bucket\"}"
      }
     ]
    },
    {
     "title": "JVM Thread States",
     "type": "timeseries",
     "description": "The current number of threads having NEW state",
     "gridPos": { "h": 6, "w": 8, "x": 9, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_states_threads{cluster_name=\"$cluster\",bucket=~\"$bucket\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Pool Buffer Capacity",
     "type": "timeseries",
     "description": "An estimate of the total capacity of the buffers in this pool",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_buffer_total_capacity_bytes{cluster_name=\"$cluster\",bucket=~\"$bucket\"}",
       "legendFormat": "{{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Bytes Used (heap)",
     "type": "timeseries",
     "description": "The amount of used memory",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{cluster_name=\"$cluster\",bucket=~\"$bucket\",area=\"heap\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Memory Bytes Max (heap)",
     "type": "timeseries",
     "description": "The maximum amount of memory in bytes that can be used for memory management",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_max_bytes{cluster_name=\"$cluster\",bucket=~\"$bucket\",area=\"heap\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Memory Utilization (nonheap)",
     "type": "timeseries",
     "description": "The memory used / memory max.  Values with a -1 max are excluded, as they are unlimited",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{cluster_name=\"$cluster\",bucket=~\"$bucket\",area=\"nonheap\"}\n/\njvm_memory_max_bytes{cluster_name=\"$cluster\",bucket=~\"$bucket\",area=\"nonheap\"} > 0",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Memory Bytes Used (nonheap)",
     "type": "timeseries",
     "description": "The amount of used memory",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{cluster_name=\"$cluster\",bucket=~\"$bucket\",area=\"nonheap\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Memory Bytes Max (nonheap)",
     "type": "timeseries",
     "description": "The maximum amount of memory in bytes that can be used for memory management",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_max_bytes{cluster_name=\"$cluster\",bucket=~\"$bucket\",area=\"nonheap\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Memory Utilization (heap)",
     "type": "timeseries",
     "description": "The memory used / memory max.  Values with a -1 max are excluded, as they are unlimited",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{cluster_name=\"$cluster\",bucket=~\"$bucket\",area=\"heap\"}\n/\njvm_memory_max_bytes{cluster_name=\"$cluster\",bucket=~\"$bucket\",area=\"heap\"} > 0",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Memory Bytes Committed (heap)",
     "type": "timeseries",
     "description": "The amount of memory in bytes that is committed for the Java virtual machine to use",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_committed_bytes{cluster_name=\"$cluster\",bucket=~\"$bucket\",area=\"heap\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Memory Bytes Committed (nonheap)",
     "type": "timeseries",
     "description": "The amount of memory in bytes that is committed for the Java virtual machine to use",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_committed_bytes{cluster_name=\"$cluster\",bucket=~\"$bucket\",area=\"nonheap\"}",
       "legendFormat": "{{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Live Data Size",
     "type": "stat",
     "description": "Size of long-lived heap memory pool after reclamation",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_gc_live_data_size_bytes{cluster_name=\"$cluster\",bucket=~\"$bucket\"}"
      }
     ]
    },
    {
     "title": "GC Pool Increases (Before/After)",
     "type": "stat",
     "description": "Count of positive increases in the size of the old generation memory pool before GC to after GC",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(jvm_gc_memory_promoted_bytes_total{cluster_name=\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "JVM GC Allocated Bytes",
     "type": "timeseries",
     "description": "Incremented for an increase in the size of the (young) heap memory pool after one GC to before the next",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "increase(jvm_gc_memory_allocated_bytes_total{cluster_name=\"$cluster\",bucket=~\"$bucket\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC Pause Time",
     "type": "timeseries",
     "description": "Time spent in GC pause",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_max{cluster_name=\"$cluster\",bucket=~\"$bucket\"}",
       "legendFormat": "{{cause}}"
      }
     ]
    }
   ]
  }
 ]
}