{
 "title": "Couchbase Logs - HTTP Access Log Overview",
 "tags": [
  "couchbase",
  "logs",
  "loki",
  "http",
  "http_access"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({file=\"slow_query.log\"}, couchbase_cluster_name)"
   },
   {
    "name": "file",
    "label": "File",
    "query": "label_values({couchbase_cluster_name=\"$cluster\",file=~\"http_.+\"}, file)"
   },
   {
    "name": "level",
    "label": "Level",
    "query": "label_values({file=\"http_access.log\",couchbase_cluster_name=~\"$cluster\"}, level)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values({file=\"http_access.log\",couchbase_cluster_name=~\"$cluster\"}, couchbase_node)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Audit Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages by Log Level/sec",
   "type": "timeseries",
   "description": "The number of log messages per second, by log level",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (level) (\n  rate(\n    {couchbase_cluster_name=\"$cluster\", file=\"$file\", level=~\"$level\",couchbase_node=~\"$node\"} [$interval]\n  )\n)",
     "legendFormat": "{{level}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "Total Messages by Log Level",
   "type": "piechart",
   "description": "The number of log messages by level in the range",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (level) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"$file\", level=~\"$level\",couchbase_node=~\"$node\"} [$__range]\n  )\n)",
     "legendFormat": "{{level}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "Total Messages by Response Code",
   "type": "piechart",
   "description": "The number of log messages by level in the range",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"$file\", level=~\"$level\", couchbase_node=~\"$node\"} [$__range]\n    | json \n  )\n)",
     "legendFormat": "{{status}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "HTTP Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"$file\", level=~\"$level\",couchbase_node=~\"$node\"} [$interval]\n    | json \n  )\n)",
     "legendFormat": "{{status}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "HTTP Log Entries by Node/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (couchbase_node) (\n  rate(\n    {couchbase_cluster_name=\"$cluster\", file=\"$file\", level=~\"$level\",couchbase_node=~\"$node\"} [$interval]\n  )\n)",
     "legendFormat": "{{couchbase_node}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "HTTP Requests by User",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum by(user) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"$file\", level=~\"$level\",couchbase_node=~\"$node\"} \n    | json\n    | label_format user=`{{ .user | replace \"-\" \"Anonymous\" }}`\n    | __error__=\"\" [$__interval]\n  )\n)",
     "legendFormat": "{{name}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "HTTP Request Method",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (method) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"$file\", level=~\"$level\",couchbase_node=~\"$node\"} [$interval]\n    | json \n  )\n)",
     "legendFormat": "{{status}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "HTTP Log Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (couchbase_node) (\n  bytes_rate(\n    {couchbase_cluster_name=\"$cluster\", file=\"$file\", level=~\"$level\",couchbase_node=~\"$node\"} [$interval]\n  )\n)",
     "legendFormat": "{{couchbase_node}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "Top 10 Requested Paths",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "topk(10, \n  sum by(path) (\n    count_over_time(\n      {couchbase_cluster_name=\"$cluster\", file=\"$file\", level=~\"$level\",couchbase_node=~\"$node\"} \n      | json\n      | __error__=\"\" [$__range]\n    )\n  )\n)",
     "legendFormat": "{{path}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "Top 10 Requesting Hosts",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "topk(10, \n  sum by(host) (\n    count_over_time(\n      {couchbase_cluster_name=\"$cluster\", file=\"$file\", level=~\"$level\",couchbase_node=~\"$node\"} \n      | json\n      | __error__=\"\" [$__range]\n    )\n  )\n)",
     "legendFormat": "{{path}}",
     "resolution": 5
    }
   ]
  }
 ]
}