{
 "title": "Couchbase Logs - Indexer Logs Overview",
 "description": "A Dashboard for an Overview of the Couchbase Data Service Logs",
 "tags": [
  "couchbase",
  "logs",
  "loki",
  "index",
  "indexer",
  "gsi",
  "moi"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({file=\"slow_query.log\"}, couchbase_cluster_name)"
   },
   {
    "name": "level",
    "label": "Level",
    "query": "label_values({couchbase_cluster_name=\"$cluster\",file=~\"memcached.log\"}, level)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values({couchbase_cluster_name=\"$cluster\",file=\"memcached.log\",level=~\"$level\"}, couchbase_node)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "file", "query": "indexer.log" }
  ]
 },
 "panels": [
  {
   "title": "Total Indexer Messages by Log Level",
   "type": "piechart",
   "description": "The total number of entries by log level",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (level) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"$file\", couchbase_node=~\"$node\",level=~\"$level\"} [$__range]\n  )\n)",
     "legendFormat": "{{level}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "Indexer Messages by Log Level/sec",
   "type": "timeseries",
   "description": "The total number of entries by log level per second",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (level) (\n  rate(\n    {couchbase_cluster_name=\"$cluster\", file=\"$file\", couchbase_node=~\"$node\",level=~\"$level\"} [$interval]\n  )\n)",
     "legendFormat": "{{bucket}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "Indexer Log Bytes by Node/sec",
   "type": "timeseries",
   "description": "That total number of bytes ",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (couchbase_node) (\n  bytes_rate(\n    {couchbase_cluster_name=\"$cluster\", file=\"$file\", couchbase_node=~\"$node\",level=~\"$level\"} [$interval]\n  )\n)",
     "legendFormat": "{{bucket}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "Total Indexer Messages by Component",
   "type": "piechart",
   "description": "The number of Indexer messages by component",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (component) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"$file\", couchbase_node=~\"$node\",level=~\"$level\"} \n    | json \n    | __error__=\"\" [$__range]\n  )\n)",
     "legendFormat": "{{level}} - {{component}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Indexer Messages by Component",
   "type": "timeseries",
   "description": "The total number of entries by log level per second",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (component) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"$file\", couchbase_node=~\"$node\",level=~\"$level\"} \n    | json \n    | __error__=\"\" [$interval]\n  )\n)",
     "legendFormat": "{{bucket}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "Total Indexer Messages by Component",
   "type": "table",
   "description": "The number of Indexer messages by component",
   "gridPos": { "h": 16, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (level, component) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"$file\", couchbase_node=~\"$node\",level=~\"$level\"} \n    | json \n    | __error__=\"\" [$__range]\n  )\n)",
     "legendFormat": "{{level}} - {{message_type}}",
     "resolution": 1
    }
   ]
  }
 ]
}