{
 "title": "Couchbase Index Details",
 "tags": [
  "couchbase",
  "couchbase-7",
  "couchbase-service",
  "index",
  "gsi",
  "moi"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(index_memory_quota,cluster_name)"
    }
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": {
     "query": "label_values(index_num_requests{cluster_name=~\"$cluster\"},bucket)"
    }
   },
   {
    "name": "scope",
    "label": "Scope",
    "query": {
     "query": "label_values(index_num_requests{cluster_name=~\"$cluster\", bucket=~\"$bucket\"},scope)"
    }
   },
   {
    "name": "collection",
    "label": "Collection",
    "query": {
     "query": "label_values(index_num_requests{cluster_name=~\"$cluster\", bucket=~\"$bucket\",scope=~\"$scope\"},collection)"
    }
   },
   {
    "name": "index",
    "label": "Index",
    "query": {
     "query": "label_values(index_num_requests{cluster_name=~\"$cluster\",bucket=~\"$bucket\",scope=~\"$scope\",collection=~\"$collection\",index!~\".*\\\\(replica [0-9]+\\\\)\"},index)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Bucket Indexes Overview",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "index_memory_used{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "index_items_count{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}",
     "legendFormat": "Item Count"
    },
    {
     "expr": "index_avg_scan_latency{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}",
     "legendFormat": "Avg. Scan Latency"
    },
    {
     "expr": "index_resident_percent{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}",
     "legendFormat": "Avg. Resident Ratio"
    },
    {
     "expr": "rate(index_num_requests{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}[$__rate_interval])",
     "legendFormat": "Avg. Scans / Sec"
    },
    {
     "expr": "index_avg_item_size{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}",
     "legendFormat": "Avg. Item Size"
    },
    {
     "expr": "index_data_size_on_disk{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}",
     "legendFormat": "Size On Disk"
    }
   ]
  },
  {
   "title": "Index: $index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "index",
   "collapsed": true,
   "panels": [
    {
     "title": "Index Items Count",
     "type": "timeseries",
     "description": "The number of items in the index\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "index_items_count{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Average Item Size",
     "type": "timeseries",
     "description": "The average index entry size\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "index_avg_item_size{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Cache Hits",
     "type": "timeseries",
     "description": "The number of in-memory hits to the index\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(index_cache_hits{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}[$__rate_interval])",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Cache Misses",
     "type": "timeseries",
     "description": "The number of in-memory misses to the index\n",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(index_cache_misses{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}[$__rate_interval])",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "timeseries",
     "description": "The amount of memory used by the index\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "index_memory_used{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Average Scan Latency",
     "type": "timeseries",
     "description": "The average latency when scanning the index\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "index_avg_scan_latency{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Index Resident Percent",
     "type": "timeseries",
     "description": "The percentage of the index that is memory resident.  Indexes w/ 0 items are omitted\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "index_resident_percent{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Disk Size",
     "type": "timeseries",
     "description": "The size of the index on disk\n",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "index_disk_size{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Indexed Documents/sec",
     "type": "timeseries",
     "description": "The number of items indexed since the last restart\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(index_num_docs_indexed{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}[$__rate_interval])",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Pending Documents",
     "type": "timeseries",
     "description": "The number of documents that are pending\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "index_num_docs_pending{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Queued Documents",
     "type": "timeseries",
     "description": "The number of documents that are queued for indexing\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "index_num_docs_queued{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Index Fragmentation Percentage",
     "type": "timeseries",
     "description": "The index fragmentation percentage\n",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "index_frag_percent{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Num Requests/sec",
     "type": "timeseries",
     "description": "The number of requests to the index\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(index_num_requests{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}[$__rate_interval])",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Data Size",
     "type": "timeseries",
     "description": "The total data size of the index\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "index_data_size{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Records in Memory",
     "type": "timeseries",
     "description": "The number of records in the index that are in memory\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "index_recs_in_mem{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Scan Duration/sec",
     "type": "timeseries",
     "description": "The total time spent scanning",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(index_total_scan_duration{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}[$__rate_interval])",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Rows Returned/sec",
     "type": "timeseries",
     "description": "The average number of rows returned by a scan\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(index_num_rows_returned{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}[$__rate_interval])",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Scan Bytes Read/sec",
     "type": "timeseries",
     "description": "The average number of bytes read per scan\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(index_scan_bytes_read{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}[$__rate_interval])",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Records on Disk",
     "type": "timeseries",
     "description": "The number of records not in memory\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "index_recs_on_disk{cluster_name=~\"$cluster\",bucket=~\"$bucket\",index=~\"($index)( \\\\(replica.*)?\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  }
 ]
}