{
 "title": "Couchbase Logs - Viewer",
 "description": "A Dashboard to allow easy search of the Couchbase slow query logs ",
 "tags": [
  "couchbase",
  "logs",
  "data",
  "kv",
  "n1ql",
  "query",
  "analytics",
  "fts",
  "search",
  "eventing",
  "xdcr",
  "audit",
  "loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({file=\"slow_query.log\"}, couchbase_cluster_name)"
   },
   {
    "name": "file",
    "label": "File",
    "query": "label_values({couchbase_cluster_name=\"$cluster\",file!=\"slow_query.log\"}, file)"
   },
   {
    "name": "level",
    "label": "Level",
    "query": "label_values({couchbase_cluster_name=\"$cluster\",file=~\"$file\"}, level)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values({couchbase_cluster_name=\"$cluster\",file=~\"$file\",level=~\"$level\"}, couchbase_node)"
   },
   { "name": "search", "label": "Search" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Logs Matching",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=~\"$file\", level=~\"$level\", couchbase_node=~\"$node\"}\n    |~ \"(?i)$search\"  [$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Log File Names",
   "type": "timeseries",
   "description": "The total number of entries by log level per second",
   "gridPos": { "h": 5, "w": 8, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (file) (\n  rate(\n    {couchbase_cluster_name=\"$cluster\", file=~\"$file\", level=~\"$level\",couchbase_node=~\"$node\"} \n    |~ \"(?i)$search\"  [$interval]\n  )\n)",
     "legendFormat": "{{file}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "timeseries",
   "description": "The total number of entries by log level per second",
   "gridPos": { "h": 5, "w": 8, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (level) (\n  rate(\n    {couchbase_cluster_name=\"$cluster\", file=~\"$file\", level=~\"$level\",couchbase_node=~\"$node\"} \n    |~ \"(?i)$search\"  [$interval]\n  )\n)",
     "legendFormat": "{{bucket}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "Logs ",
   "type": "logs",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{couchbase_cluster_name=\"$cluster\", file=~\"$file\", level=~\"$level\"} \n|~ \"(?i)$search\""
    }
   ]
  }
 ]
}