{
 "title": "System Processes Metrics",
 "description": "Show Linux Process information as captured by  https://github.com/ncabatoff/process-exporter  designed for PMM",
 "tags": [
  "Insight",
  "Processes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(namedprocess_namegroup_cpu_seconds_total, cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(namedprocess_namegroup_cpu_seconds_total{cluster_name=~\"$cluster\"}, instance)"
    }
   },
   {
    "name": "processes",
    "label": "Processes",
    "query": {
     "query": "label_values(namedprocess_namegroup_cpu_seconds_total{cluster_name=~\"$cluster\",instance=~\"$node\"},groupname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Process CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top processes by Total CPU cores used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(5, \n  sum(\n    rate(\n      namedprocess_namegroup_cpu_seconds_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\",mode=~\"user|system\"}[$__rate_interval]\n    ) \n  ) by (instance, groupname)\n  or \n  sum(\n    irate(\n      namedprocess_namegroup_cpu_seconds_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\",mode=~\"user|system\"}[$__rate_interval]\n    )\n  ) by (instance, groupname)\n)",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top processes by System CPU cores used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(5,\n  rate(namedprocess_namegroup_cpu_seconds_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\",mode=\"system\"}[$__rate_interval])\n  or \n  irate(namedprocess_namegroup_cpu_seconds_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\",mode=\"system\"}[$__rate_interval])\n)",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top processes by Used  memory",
     "type": "timeseries",
     "description": "Used Memory means the space process consumes in RAM plus space it consumes in the swap space. Note, this metric is different from Virtual Memory, which also includes virtual space which was assigned to the process but never really allocated.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(5,\n  (\n    (\n      avg_over_time(namedprocess_namegroup_memory_bytes{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\",memtype=\"swapped\"}[$__rate_interval])\n      + \n      ignoring (memtype) avg_over_time(namedprocess_namegroup_memory_bytes{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\",memtype=\"resident\"}[$__rate_interval])\n    )\n    or\n    (\n      avg_over_time(namedprocess_namegroup_memory_bytes{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\",memtype=\"swapped\"}[$__rate_interval])\n      + \n      ignoring (memtype) avg_over_time(namedprocess_namegroup_memory_bytes{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\",memtype=\"resident\"}[$__rate_interval])\n    )\n  )\n)",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "Top processes by Resident Memory",
     "type": "timeseries",
     "description": "Resident Memory means the memory process (or technically group of processes) takes in physical RAM.  The \"Proportional\" means the method by how this consumption is counted. A single page in RAM sometimes is shared by multiple processes, and Proportional means it is divided up among all processes sharing it when memory allocation is accounted for rather than counted as part of every process. This ensures there is no double counting and you should not see total size of Resident memory for your processes well in excess of the physical memory you have.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(5,\n  (\n    avg_over_time(namedprocess_namegroup_memory_bytes{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\",memtype=\"resident\"}[$__rate_interval]) \n    or\n    avg_over_time(namedprocess_namegroup_memory_bytes{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\",memtype=\"resident\"}[$__rate_interval])\n  )\n)",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "Top processes by Virtual memory",
     "type": "timeseries",
     "description": "Virtual Memory is the virtual address space that was allocated to process. In some cases, it will be close to memory used, and in other cases, it may be very different.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(5,\n  (\n    avg_over_time(namedprocess_namegroup_memory_bytes{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\",memtype=\"virtual\"}[$__rate_interval])\n    or\n    avg_over_time(namedprocess_namegroup_memory_bytes{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\",memtype=\"virtual\"}[$__rate_interval])\n  )\n)",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "Top processes by Swapped Memory",
     "type": "timeseries",
     "description": "Swapped Memory shows us which processes are swapped out and by how much.  I would pay special attention to this graph because if the Swap Activity panel shows serious IO going on, this means system performance might be significantly impacted. If unused processes are swapped out, or even some unused portions of the processes, it is not the problem. ",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(5,\n  (\n    avg_over_time(namedprocess_namegroup_memory_bytes{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\",memtype=\"swapped\"}[$__rate_interval])\n    or\n    avg_over_time(namedprocess_namegroup_memory_bytes{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\",memtype=\"swapped\"}[$__rate_interval])\n  )\n)",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Disk IO Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top processes by Bytes Written",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "topk(5,\n  (\n    rate(namedprocess_namegroup_write_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\"}[$__rate_interval]) \n    or \n    irate(namedprocess_namegroup_write_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\"}[$__rate_interval])\n  )\n)",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "Top processes by Bytes Read",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "topk(5,\n  (\n    rate(namedprocess_namegroup_read_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\"}[$__rate_interval]) \n    or \n    irate(namedprocess_namegroup_read_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\"}[$__rate_interval])\n  )\n)",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process and Thread Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top processes by number of  processes instances",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,\n  (\n    max_over_time(namedprocess_namegroup_num_procs{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\"}[$__rate_interval]) \n  )\n)",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "Top processes by number of threads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,\n  (\n    max_over_time(namedprocess_namegroup_num_threads{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\"}[$__rate_interval]) \n  )\n)",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  },
  { "title": "Process Context Switches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Top Processes by Voluntary Context Switches",
   "type": "timeseries",
   "description": "A high number of Voluntary Context Switches (hundreds of thousands and millions per second) may indicate heavy contention, or it may just correspond to a high number of requests being served by the process, as in many architectures starting/stopping request handling requires a context switch.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5,\n  (\n    rate(namedprocess_namegroup_context_switches_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\",ctxswitchtype=\"voluntary\"}[$__rate_interval]) \n    or\n    irate(namedprocess_namegroup_context_switches_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\",ctxswitchtype=\"voluntary\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top Processes by  Non-Voluntary Context Switches",
   "type": "timeseries",
   "description": "A high number of Non-Voluntary Context Switches, on the other hand, can correspond to not having enough CPU available with processes moved off CPU by the scheduler when they have exceeded their allotted time slice, or for other reasons.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5,\n  (\n    rate(namedprocess_namegroup_context_switches_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\",ctxswitchtype=\"nonvoluntary\"}[$__rate_interval]) \n    or\n    irate(namedprocess_namegroup_context_switches_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\",ctxswitchtype=\"nonvoluntary\"}[5m])\n  )\n)",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Process File Descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top processes by Open File Descriptors",
     "type": "timeseries",
     "description": "File Descriptors show us the global limit of the file descriptors allowed in the operating system as well as for individual processes.  Running out of file descriptors for a whole system is really bad, as you will have many things start failing at random. Although on modern, powerful systems, the limit is so high you rarely hit this problem.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,\n  (\n    max_over_time(namedprocess_namegroup_open_filedesc{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\"}[$__rate_interval]) \n  )\n)",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "Top processes by File Descriptor Usage Percent",
     "type": "timeseries",
     "description": "The limit of files process can open still applies so it is very helpful to see which processes require a lot of file descriptors (by number) and also how this number compares to the total number of descriptors allowed for the process.  ",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk(5,\n  (\n    max_over_time(namedprocess_namegroup_worst_fd_ratio{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\"}[$__rate_interval]) \n  )\n) * 100",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Page Faults",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top processes by Major Page Faults",
     "type": "timeseries",
     "description": "Major page faults are relatively expensive, typically causing disk IO when they happen.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk(5,\n  (\n    rate(namedprocess_namegroup_major_page_faults_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\"}[$__rate_interval]) \n    or\n    irate(namedprocess_namegroup_major_page_faults_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\"}[$__rate_interval])\n  )\n)",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "Top processes by Minor Page Faults",
     "type": "timeseries",
     "description": "Minor page faults are less expensive, corresponding to accessing pages that are not mapped to the given process address space but otherwise are in memory.  Minor page faults are less expensive, requiring a switch to kernel mode and for the kernel to do some housekeeping.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk(5,\n  (\n    rate(namedprocess_namegroup_minor_page_faults_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\"}[$__rate_interval]) \n    or\n    irate(namedprocess_namegroup_minor_page_faults_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\"}[$__rate_interval])\n  )\n)",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Statuses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top running processes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,\n  max_over_time(namedprocess_namegroup_states{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\",state=\"Running\"}[$__rate_interval]) \n)",
       "legendFormat": "{{groupname}}"
      }
     ]
    },
    {
     "title": "Top of processes waiting on IO",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,\n  max_over_time(namedprocess_namegroup_states{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\",state=\"Waiting\"}[$__rate_interval])\n)",
       "legendFormat": "{{groupname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Kernel Waits (WCHAN)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kernel waits for $processes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,\n  sum(\n    avg_over_time(namedprocess_namegroup_threads_wchan{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\"}[$__rate_interval])\n  ) by (wchan) \n)",
       "legendFormat": "{{wchan}}"
      }
     ]
    },
    {
     "title": "Kernel wait Details for $processes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,\n  sum(\n    avg_over_time(namedprocess_namegroup_threads_wchan{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"$processes\"}[$__rate_interval])\n  ) by (wchan,groupname) \n)",
       "legendFormat": "{{groupname}} : {{wchan}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes by uptime",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "time()-(\n  namedprocess_namegroup_oldest_start_time_seconds{cluster_name=~\"$cluster\",instance=~\"$node\"} > 0\n)"
      }
     ]
    }
   ]
  }
 ]
}