{
 "title": "Prometheus Overview",
 "tags": [
  "prometheus",
  "monitoring"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(prometheus_tsdb_head_samples_appended_total, instance)"
    }
   },
   {
    "name": "slice",
    "query": {
     "query": "label_values(prometheus_engine_query_duration_seconds{instance=\"$node\"},slice)"
    }
   },
   {
    "name": "handler",
    "query": {
     "query": "label_values(prometheus_http_request_duration_seconds_count{instance=\"$node\",handler!~\".*(\\\\.ico|\\\\.js|static).*\"},handler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Config",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Build Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_build_info{instance=\"$node\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Last Successful Config Reload",
   "type": "stat",
   "description": "Timestamp of the last successful configuration reload.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - prometheus_config_last_reload_success_timestamp_seconds{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Last Config Reload Successful",
   "type": "stat",
   "description": "Whether the last configuration reload attempt was successful.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_config_last_reload_successful{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Query Log Enabled",
   "type": "stat",
   "description": "State of the query log.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_engine_query_log_enabled{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "AlertManagers Discovered",
   "type": "stat",
   "description": "The number of alertmanagers discovered and active.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_notifications_alertmanagers_discovered{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Scrape Jobs",
   "type": "stat",
   "description": "The total number of scrape jobs",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(prometheus_target_scrape_pool_targets)"
    }
   ]
  },
  {
   "title": "Scrape Targets",
   "type": "stat",
   "description": "The total number of scrape targets",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_target_scrape_pool_targets{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Local Storage Block Size",
   "type": "stat",
   "description": "The number of bytes that are currently used for local storage by all blocks.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes{instance=\"$node\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Series in Head Block",
   "type": "stat",
   "description": "Total number of series in the head block.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Head Chunks",
   "type": "stat",
   "description": "Total number of chunks in the head block.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{instance=\"$node\"}",
     "legendFormat": "Chunks"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "stat",
   "description": "Average Scrape Duration",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(scrape_duration_seconds)" }
   ]
  },
  {
   "title": "Scrape Samples Scraped",
   "type": "stat",
   "description": " the number of samples the targets exposed.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(scrape_samples_scraped)" }
   ]
  },
  {
   "title": "Avg. Rule Evaluation Duration",
   "type": "stat",
   "description": "The average amount of time for all rule evaluations",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(prometheus_rule_group_last_duration_seconds{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "Target Uptime",
   "type": "gauge",
   "description": "The average upness in the range of the scrape target for all jobs",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{instance=~\"$node\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Scrape Targets Down",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up == 0)\nor\nvector(0)" }
   ]
  },
  {
   "title": "Query Saturation",
   "type": "gauge",
   "description": "The current number of queries being executed or waiting / The max number of concurrent queries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_engine_queries{instance=\"$node\"} / prometheus_engine_queries_concurrent_max{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Metric Handler Requests/sec",
   "type": "stat",
   "description": "Total number of scrapes by HTTP status code.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(promhttp_metric_handler_requests_total[$__rate_interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Avg. Query Engine Duration",
   "type": "stat",
   "description": "The total average time for all query slices",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(prometheus_engine_query_duration_seconds_sum{instance=\"$node\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Notifications Sent/sec",
   "type": "stat",
   "description": "Total number of alerts sent.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(prometheus_notifications_sent_total{instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "Notifications"
    }
   ]
  },
  {
   "title": "Insights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top 10 Metric Series",
     "type": "table",
     "description": "Which metrics have the highest number of series.  ",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "topk(10, count by (__name__, job)({__name__=~\".+\"}))"
      }
     ]
    },
    {
     "title": "Top 10 Metric Series by Job",
     "type": "table",
     "description": "Which metrics have the highest number of series per job",
     "gridPos": { "h": 8, "w": 6, "x": 10, "y": 18 },
     "targets": [
      {
       "expr": "topk(10, count by (job)({__name__=~\".+\", job=~\".+\"}))"
      }
     ]
    },
    {
     "title": "Top 10 Slowest Scrape Targets (All Jobs)",
     "type": "table",
     "description": "Which targets have the slowest scrape average time across all jobs",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "targets": [
      {
       "expr": "topk(10, avg by (instance) (scrape_duration_seconds))"
      }
     ]
    },
    {
     "title": "Top 10 Slowest Scrape Targets (All Jobs)",
     "type": "table",
     "description": "Which targets have the slowest scrape average time across all jobs",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "topk(10, avg by (instance, job) (scrape_duration_seconds))"
      }
     ]
    },
    {
     "title": "Top 10 Slowest Scrape Jobs",
     "type": "table",
     "description": "Which jobs have the slowest scrape average time across all targets",
     "gridPos": { "h": 8, "w": 6, "x": 10, "y": 26 },
     "targets": [
      {
       "expr": "topk(10, avg by (job) (scrape_duration_seconds))"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors, Failures & Warnings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Failed Connections",
     "type": "stat",
     "description": "Total number of connections failed to dial by the dialer a given name.",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(net_conntrack_dialer_conn_failed_total{instance=~\"$node\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Checkpoint Failures",
     "type": "stat",
     "description": "The total number of checkpoints failures",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\nincrease(prometheus_tsdb_checkpoint_creations_failed_total{instance=\"$node\"}[$__range])\n+\nincrease(prometheus_tsdb_checkpoint_deletions_failed_total{instance=\"$node\"}[$__range])\n)",
       "legendFormat": "Checkpoint Failures"
      }
     ]
    },
    {
     "title": "Rule Evaluation Failures",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n    increase(prometheus_rule_evaluation_failures_total{instance=\"$node\"}[$__range])\n)",
       "legendFormat": "Evaluation "
      }
     ]
    },
    {
     "title": "Service Discovery Errors",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n    (increase(prometheus_sd_azure_refresh_failures_total{instance=\"$node\"}[$__range]) or vector(0))\n    +\n    (increase(prometheus_sd_consul_rpc_failures_total{instance=\"$node\"}[$__range]) or vector(0))\n    +\n    (increase(prometheus_sd_dns_lookup_failures_total{instance=\"$node\"}[$__range]) or vector(0))\n    +\n    (increase(prometheus_sd_ec2_refresh_failures_total{instance=\"$node\"}[$__range]) or vector(0))\n    +\n    (increase(prometheus_sd_gce_refresh_failures_total{instance=\"$node\"}[$__range]) or vector(0))\n    +\n    (increase(prometheus_sd_marathon_refresh_failures_total{instance=\"$node\"}[$__range]) or vector(0))\n    +\n    (increase(prometheus_sd_openstack_refresh_failures_total{instance=\"$node\"}[$__range]) or vector(0))\n    +\n    (increase(prometheus_sd_triton_refresh_failures_total{instance=\"$node\"}[$__range]) or vector(0))\n    +\n    (increase(prometheus_sd_file_read_errors_total{instance=\"$node\"}[$__range]) or vector(0))\n    +\n    (increase(prometheus_sd_kuma_fetch_failures_total{instance=\"$node\"}[$__range]) or vector(0))\n    +\n    (prometheus_sd_failed_configs{instance=\"$node\"} or vector(0))\n)",
       "legendFormat": "Failures"
      }
     ]
    },
    {
     "title": "Target Scrape Failures",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n    (increase(prometheus_target_scrapes_exceeded_body_size_limit_total{instance=\"$node\"}[$__range]) or vector(0))\n    + \n    (increase(prometheus_target_scrapes_exceeded_sample_limit_total{instance=\"$node\"}[$__range]) or vector(0))\n    +\n    (increase(prometheus_target_scrapes_sample_duplicate_timestamp_total{instance=\"$node\"}[$__range]) or vector(0))\n    +\n    (increase(prometheus_target_scrapes_sample_out_of_bounds_total{instance=\"$node\"}[$__range]) or vector(0))\n    +\n    (increase(prometheus_target_scrapes_exemplar_out_of_order_total{instance=\"$node\"}[$__range]) or vector(0))\n)",
       "legendFormat": "Failures"
      }
     ]
    },
    {
     "title": "TreeCache Zookeeper Failures",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n    (increase(prometheus_treecache_zookeeper_failures_total{instance=\"$node\"}[$__range]) or vector(0))\n)",
       "legendFormat": "Failures"
      }
     ]
    },
    {
     "title": "TSDB Compactions Failed",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 18, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_tsdb_compactions_failed_total{instance=\"$node\"}[$__rate_interval])) or vector(0)",
       "legendFormat": "Compactions Failed"
      }
     ]
    },
    {
     "title": "TSDB Head Failures ",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum( \n    increase(prometheus_tsdb_head_truncations_failed_total{instance=\"$node\"}[$__range]) or vector(0)\n    +\n    increase(prometheus_tsdb_head_series_not_found{instance=\"$node\"}[$__range]) or vector(0)\n)",
       "legendFormat": "Failures"
      }
     ]
    },
    {
     "title": "Notification Errors",
     "type": "stat",
     "description": "Total number of errors sending alert notifications.",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_notifications_errors_total{instance=\"$node\"}[$__range]))"
      }
     ]
    },
    {
     "title": "WAL Failures",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum( \n    increase(prometheus_tsdb_wal_writes_failed_total{instance=\"$node\"}[$__range]) or vector(0)\n    +\n    increase(prometheus_tsdb_wal_truncations_failed_total{instance=\"$node\"}[$__range]) or vector(0)\n    +\n    increase(prometheus_tsdb_wal_corruptions_total{instance=\"$node\"}[$__range]) or vector(0)\n)",
       "legendFormat": "Failures"
      }
     ]
    },
    {
     "title": "Query Log Failures",
     "type": "stat",
     "description": "The number of query log failures.",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_engine_query_log_failures_total{instance=\"$node\"}[$__range])"
      }
     ]
    },
    {
     "title": "Web Federation Errors",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_web_federation_errors_total{instance=\"$node\"}[$__range]))",
       "legendFormat": "Errors"
      }
     ]
    },
    {
     "title": "Snapshot Replay Errors",
     "type": "stat",
     "description": "Total number snapshot replays that failed.",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_snapshot_replay_error_total{instance=\"$node\"}[$__range])"
      }
     ]
    },
    {
     "title": "TSDB Reloads Failures ",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum( \n    increase(prometheus_tsdb_reloads_failures_total{instance=\"$node\"}[$__range]) or vector(0)\n)",
       "legendFormat": "Failures"
      }
     ]
    }
   ]
  },
  {
   "title": "TSDB Head",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Appender Transactions",
     "type": "timeseries",
     "description": "Number of currently active appender transactions",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_active_appenders{instance=\"$node\"}",
       "legendFormat": "Appended"
      }
     ]
    },
    {
     "title": "Head Chunks",
     "type": "timeseries",
     "description": "Total number of chunks in the head block.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_chunks{instance=\"$node\"}",
       "legendFormat": "Chunks"
      }
     ]
    },
    {
     "title": "Head Block Max Timestamp",
     "type": "stat",
     "description": "Maximum timestamp of the head block. ",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_max_time_seconds{instance=\"$node\"} * 1000"
      }
     ]
    },
    {
     "title": "Head Block Garbage Collection",
     "type": "timeseries",
     "description": "Runtime of garbage collection in the head block.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_head_gc_duration_seconds_sum{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Time"
      }
     ]
    },
    {
     "title": "Head Block Garbage Collection",
     "type": "timeseries",
     "description": "Runtime of garbage collection in the head block.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_head_gc_duration_seconds_sum{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Time"
      }
     ]
    },
    {
     "title": "Head Block Min Timestamp",
     "type": "stat",
     "description": "Minimum time bound of the head block.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_min_time_seconds{instance=\"$node\"} * 1000"
      }
     ]
    },
    {
     "title": "Memory-mapped Chunk Corruptions",
     "type": "stat",
     "description": "Total number of memory-mapped chunk corruptions.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_mmap_chunk_corruptions_total{instance=\"$node\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Head Samples Appended/sec",
     "type": "timeseries",
     "description": "Total number of appended samples.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_samples_appended_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Appends"
      }
     ]
    },
    {
     "title": "Oldest Timestamp Stored",
     "type": "stat",
     "description": "Lowest timestamp value stored in the database.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_tsdb_lowest_timestamp_seconds{instance=\"$node\"} * 1000"
      }
     ]
    },
    {
     "title": "TSDB Samples",
     "type": "timeseries",
     "description": "Total number of out of bound samples ingestion failed attempts.\n\nTotal number of out of order samples ingestion failed attempts.\n\nNumber of times the database failed to reloadBlocks block data from disk.\n\nNumber of times the database reloaded block data from disk.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_out_of_bound_samples_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Out of Bounds"
      },
      {
       "expr": "increase(prometheus_tsdb_out_of_order_samples_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Out of Order"
      },
      {
       "expr": "increase(prometheus_tsdb_reloads_failures_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Reload Block Failures"
      },
      {
       "expr": "increase(prometheus_tsdb_reloads_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Reloads"
      }
     ]
    },
    {
     "title": "Head Truncations",
     "type": "timeseries",
     "description": "Total number of head truncations success and  failed.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_head_truncations_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Truncations"
      }
     ]
    },
    {
     "title": "Head Chunks Created",
     "type": "timeseries",
     "description": "Total number of chunks created in the head\n\nTotal number of chunks removed in the head",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_head_chunks_created_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Created"
      },
      {
       "expr": "increase(prometheus_tsdb_head_chunks_removed_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Removed"
      }
     ]
    },
    {
     "title": "Head Series Created / Removed / Not Found",
     "type": "timeseries",
     "description": "Total number of series created, removed and not found in the head",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_head_series_created_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Created"
      },
      {
       "expr": "increase(prometheus_tsdb_head_series_removed_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Removed"
      },
      {
       "expr": "increase(prometheus_tsdb_head_series_not_found_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Not Found"
      }
     ]
    },
    {
     "title": "Block Max Bytes Exceeded ",
     "type": "stat",
     "description": "The number of times that blocks were deleted because the maximum number of bytes was exceeded.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_size_retentions_total{instance=\"$node\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Isolation Watermarks",
     "type": "stat",
     "description": "The lowest TSDB append ID that is still referenced.\n\nThe highest TSDB append ID that has been given out.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_tsdb_isolation_low_watermark{instance=\"$node\"}",
       "legendFormat": "Low watermark"
      },
      {
       "expr": "prometheus_tsdb_isolation_high_watermark{instance=\"$node\"}",
       "legendFormat": "High watermark"
      }
     ]
    },
    {
     "title": "Tombstone Recompt Block Percentiles",
     "type": "heatmap",
     "description": "The time taken to recompact blocks to remove tombstones.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "sum by(le) (increase(prometheus_tsdb_tombstone_cleanup_seconds_bucket{instance=\"$node\"}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Symbol Table Memory",
     "type": "stat",
     "description": "Size of symbol table in memory for loaded blocks",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_tsdb_symbol_table_size_bytes{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "Blocks Deleted Exceeding Timelimt",
     "type": "stat",
     "description": "The number of times that blocks were deleted because the maximum time limit was exceeded.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_time_retentions_total{instance=\"$node\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "WAL Page Flushes",
     "type": "timeseries",
     "description": "Total number of page flushes.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_wal_page_flushes_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Flushes"
      }
     ]
    },
    {
     "title": "Tombstone Recompt Block Percentiles",
     "type": "timeseries",
     "description": "The time taken to recompact blocks to remove tombstones.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (increase(prometheus_tsdb_tombstone_cleanup_seconds_bucket{instance=\"$node\"}[$__rate_interval])))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (increase(prometheus_tsdb_tombstone_cleanup_seconds_bucket{instance=\"$node\"}[$__rate_interval])))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(prometheus_tsdb_tombstone_cleanup_seconds_bucket{instance=\"$node\"}[$__rate_interval])))",
       "legendFormat": "99th Percentile"
      }
     ]
    },
    {
     "title": "Max Retention Bytes",
     "type": "stat",
     "description": "Max number of bytes to be retained in the tsdb blocks, configured 0 means disabled",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_tsdb_retention_limit_bytes{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "WAL Current Segment Index",
     "type": "stat",
     "description": "WAL segment index that TSDB is currently writing to.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_tsdb_wal_segment_current{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "WAL Fsync ",
     "type": "timeseries",
     "description": "Duration of WAL fsync.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_wal_fsync_duration_seconds{instance=\"$node\",quantile=\"0.5\"}[$__rate_interval])",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "increase(prometheus_tsdb_wal_fsync_duration_seconds{instance=\"$node\",quantile=\"0.9\"}[$__rate_interval])",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "increase(prometheus_tsdb_wal_fsync_duration_seconds{instance=\"$node\",quantile=\"0.99\"}[$__rate_interval])",
       "legendFormat": "99th Percentile"
      }
     ]
    },
    {
     "title": "Vertical Compactions",
     "type": "timeseries",
     "description": "Total number of compactions done on overlapping blocks.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_vertical_compactions_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Compactions"
      }
     ]
    },
    {
     "title": "WAL Truncation Duration",
     "type": "timeseries",
     "description": "Duration of WAL truncation.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_wal_truncate_duration_seconds_sum{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Duration"
      }
     ]
    },
    {
     "title": "WAL Truncations",
     "type": "timeseries",
     "description": "Total amount of WAL truncations",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_wal_truncations_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Truncations"
      }
     ]
    },
    {
     "title": "WAL Completed Pages",
     "type": "timeseries",
     "description": "Total number of completed pages.\n\nTotal number of WAL corruptions.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_wal_completed_pages_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Completed"
      }
     ]
    }
   ]
  },
  {
   "title": "TSDB Exemplars",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Last Exemplar Timestamp",
     "type": "stat",
     "description": "The timestamp of the oldest exemplar stored in circular storage. Useful to check for what timerange the current exemplar buffer limit allows. This usually means the last timestampfor all exemplars for a typical setup. This is not true though if one of the series timestamp is in future compared to rest series.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_tsdb_exemplar_last_exemplars_timestamp_seconds{instance=\"$node\"} * 1000"
      }
     ]
    },
    {
     "title": "Exemplars",
     "type": "timeseries",
     "description": "Total number of appended exemplars.\n\nTotal number of out of order exemplar ingestion failed attempts.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_exemplar_exemplars_appended_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Appended"
      },
      {
       "expr": "increase(prometheus_tsdb_exemplar_out_of_order_exemplars_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Out of Order"
      }
     ]
    },
    {
     "title": "Exemplar Storage",
     "type": "timeseries",
     "description": "Total number of exemplars the exemplar storage can store, resizeable.\n\nNumber of exemplars currently in circular storage.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
     "targets": [
      {
       "expr": "prometheus_tsdb_exemplar_max_exemplars{instance=\"$node\"}",
       "legendFormat": "Max Exemplars"
      },
      {
       "expr": "prometheus_tsdb_exemplar_exemplars_in_storage{instance=\"$node\"}",
       "legendFormat": "Exemplars"
      }
     ]
    }
   ]
  },
  {
   "title": "TSDB Chunks & Compactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "TSDB Clean Start",
     "type": "stat",
     "description": "-1: lockfile is disabled. 0: a lockfile from a previous execution was replaced. 1: lockfile creation was clean",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_tsdb_clean_start{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "Compaction Populating Block",
     "type": "stat",
     "description": "Set to 1 when a block is currently being written to the disk.",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_tsdb_compaction_populating_block{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "Blocks Loaded",
     "type": "stat",
     "description": "Number of currently loaded data blocks",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_tsdb_blocks_loaded{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "Data Replay Duration",
     "type": "stat",
     "description": "Time taken to replay the data on disk.",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_tsdb_data_replay_duration_seconds{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "Template Expansions",
     "type": "timeseries",
     "description": "The total number of template text expansions and  failures.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "increase(prometheus_template_text_expansions_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Total"
      },
      {
       "expr": "increase(prometheus_template_text_expansion_failures_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Failures"
      }
     ]
    },
    {
     "title": "Checkpoint Creations and Deletions / Day",
     "type": "timeseries",
     "description": "The total number of checkpoints created, deleted and failed",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_checkpoint_creations_total{instance=\"$node\"}[1d])",
       "legendFormat": "Creations"
      },
      {
       "expr": "increase(prometheus_tsdb_checkpoint_deletions_total{instance=\"$node\"}[1d])",
       "legendFormat": "Deletions"
      }
     ]
    },
    {
     "title": "Compactions",
     "type": "timeseries",
     "description": "Total number of compactions that failed for the partition.\n\nTotal number of skipped compactions due to disabled auto compaction.\n\nTotal number of compactions that were executed for the partition.\n\nTotal number of triggered compactions for the partition.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_compactions_skipped_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Skipped"
      },
      {
       "expr": "increase(prometheus_tsdb_compactions_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Executed"
      },
      {
       "expr": "increase(prometheus_tsdb_compactions_triggered_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Triggered"
      }
     ]
    },
    {
     "title": "TSDB Chunk Range Heatmap",
     "type": "heatmap",
     "description": "Final time range of chunks on their first compaction",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum by(le) (prometheus_tsdb_compaction_chunk_range_seconds_bucket{instance=\"$node\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "TSDB Chunk Samples Heatmap",
     "type": "heatmap",
     "description": "Final number of samples on their first compaction",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
     "targets": [
      {
       "expr": "sum by(le) (prometheus_tsdb_compaction_chunk_samples_bucket{instance=\"$node\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "TSDB Chunk Size Heatmap",
     "type": "heatmap",
     "description": "Final size of chunks on their first compaction",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "sum by(le) (increase(prometheus_tsdb_compaction_chunk_size_bytes_bucket{instance=\"$node\"}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "TSDB Compaction Duration Heatmap",
     "type": "heatmap",
     "description": "Duration of compaction runs",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
     "targets": [
      {
       "expr": "sum by(le) (increase(prometheus_tsdb_compaction_duration_seconds_bucket{instance=\"$node\"}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "TSDB Chunk Range - Percentiles",
     "type": "timeseries",
     "description": "Final time range of chunks on their first compaction",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (increase(prometheus_tsdb_compaction_chunk_range_seconds_bucket{instance=\"$node\"}[$__range])))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (increase(prometheus_tsdb_compaction_chunk_range_seconds_bucket{instance=\"$node\"}[$__range])))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (increase(prometheus_tsdb_compaction_chunk_range_seconds_bucket{instance=\"$node\"}[$__range])))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (increase(prometheus_tsdb_compaction_chunk_range_seconds_bucket{instance=\"$node\"}[$__range])))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, sum by (le) (increase(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__range])))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "TSDB Chunk Samples - Percentiles",
     "type": "timeseries",
     "description": "Final number of samples on their first compaction",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (increase(prometheus_tsdb_compaction_chunk_samples_bucket{instance=\"$node\"}[$__range])))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (increase(prometheus_tsdb_compaction_chunk_samples_bucket{instance=\"$node\"}[$__range])))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (increase(prometheus_tsdb_compaction_chunk_samples_bucket{instance=\"$node\"}[$__range])))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (increase(prometheus_tsdb_compaction_chunk_samples_bucket{instance=\"$node\"}[$__range])))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, sum by (le) (increase(kv_cmd_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__range])))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "TSDB Chunk Samples - Percentiles",
     "type": "timeseries",
     "description": "Final size of chunks on their first compaction",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (increase(prometheus_tsdb_compaction_chunk_size_bytes_bucket{instance=\"$node\"}[$__range])))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (increase(prometheus_tsdb_compaction_chunk_size_bytes_bucket{instance=\"$node\"}[$__range])))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (increase(prometheus_tsdb_compaction_chunk_size_bytes_bucket{instance=\"$node\"}[$__range])))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (increase(prometheus_tsdb_compaction_chunk_size_bytes_bucket{instance=\"$node\"}[$__range])))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, sum by (le) (increase(prometheus_tsdb_compaction_chunk_size_bytes_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__range])))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    },
    {
     "title": "TSDB Compaction Duration - Percentiles",
     "type": "timeseries",
     "description": "Duration of compaction runs",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (increase(prometheus_tsdb_compaction_duration_seconds_bucket{instance=\"$node\"}[$__range])))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (increase(prometheus_tsdb_compaction_duration_seconds_bucket{instance=\"$node\"}[$__range])))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (increase(prometheus_tsdb_compaction_duration_seconds_bucket{instance=\"$node\"}[$__range])))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (increase(prometheus_tsdb_compaction_duration_seconds_bucket{instance=\"$node\"}[$__range])))",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.999, sum by (le) (increase(prometheus_tsdb_compaction_duration_seconds_bucket{cluster_name=~\"$cluster\",bucket=~\"$bucket\",opcode=~\"$opcode\",instance=~\"$node\"}[$__range])))",
       "legendFormat": "99.9th Percentile"
      }
     ]
    }
   ]
  },
  {
   "title": "Targets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Scrape Targets",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "prometheus_target_scrape_pool_targets{instance=\"$node\"}"
      },
      {
       "expr": "label_replace(count by (job) (count by (job, instance) (up) == 1), \"scrape_job\", \"$1\", \"job\", \"(.+)\")",
       "legendFormat": "Up"
      },
      {
       "expr": "label_replace(count by (job) (count by (job, instance) (up)) - count by (job) (count by (job, instance) (up) == 1), \"scrape_job\", \"$1\", \"job\", \"(.+)\")",
       "legendFormat": "Down"
      }
     ]
    },
    {
     "title": "Scrape Duration",
     "type": "timeseries",
     "description": "Average scrape duration time",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (job) (scrape_duration_seconds)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Scrape Series Added",
     "type": "timeseries",
     "description": "the approximate number of new series in this scrape",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job) (scrape_series_added)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Target Scrapes Exceeded / Rejects",
     "type": "timeseries",
     "description": "Total number of scrapes that hit the body size limit\n\nTotal number of scrapes that hit the sample limit and were rejected.\n\nTotal number of exemplar rejected due to not being out of the expected order.\n\nTotal number of samples rejected due to duplicate timestamps but different values.\n\nTotal number of samples rejected due to timestamp falling outside of the time bounds.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(prometheus_target_scrapes_exceeded_body_size_limit_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Body Size Limit"
      },
      {
       "expr": "increase(prometheus_target_scrapes_exceeded_sample_limit_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Sample Limit"
      },
      {
       "expr": "increase(prometheus_target_scrapes_exemplar_out_of_order_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Exemplar Out of Order"
      },
      {
       "expr": "increase(prometheus_target_scrapes_sample_duplicate_timestamp_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Duplicate Timestamps"
      },
      {
       "expr": "increase(prometheus_target_scrapes_sample_out_of_bounds_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Sample Out of Bounds"
      }
     ]
    },
    {
     "title": "Scrape Samples Scraped",
     "type": "timeseries",
     "description": "Total samples scraped per scrape",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job) (scrape_samples_scraped)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Scrape Samples Dropped from Label Renaming",
     "type": "timeseries",
     "description": "the number of samples dropped when metric relabeling was applied.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job) (scrape_samples_scraped) - sum by (job) (scrape_samples_post_metric_relabeling)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Actual Target Interval - Percentiles",
     "type": "timeseries",
     "description": "Actual intervals between scrapes.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "prometheus_target_interval_length_seconds{instance=\"$node\",quantile=\"0.5\"}",
       "legendFormat": "{{interval}} - 50th"
      },
      {
       "expr": "prometheus_target_interval_length_seconds{instance=\"$node\",quantile=\"0.9\"}",
       "legendFormat": "{{interval}} - 50th"
      },
      {
       "expr": "prometheus_target_interval_length_seconds{instance=\"$node\",quantile=\"0.99\"}",
       "legendFormat": "{{interval}} - 99th"
      }
     ]
    },
    {
     "title": "Target Metadata Cache Entries",
     "type": "timeseries",
     "description": "Total number of metric metadata entries in the cache",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_target_metadata_cache_entries{instance=\"$node\"}",
       "legendFormat": "{{scrape_job}}"
      }
     ]
    },
    {
     "title": "Target Metadata Cache Size",
     "type": "timeseries",
     "description": "The number of bytes that are currently used for storing metric metadata in the cache",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "prometheus_target_metadata_cache_bytes{instance=\"$node\"}",
       "legendFormat": "{{scrape_job}}"
      }
     ]
    },
    {
     "title": "Scrape Pool Syncs",
     "type": "timeseries",
     "description": "Total number of syncs that were executed on a scrape pool.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(prometheus_target_scrape_pool_sync_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{scrape_job}}"
      }
     ]
    },
    {
     "title": "Scrape Pool Sync Interval - 99th Percentile",
     "type": "timeseries",
     "description": "Actual interval to sync the scrape pool.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "prometheus_target_sync_length_seconds{instance=\"$node\",quantile=\"0.99\"}",
       "legendFormat": "{{scrape_job}}"
      }
     ]
    },
    {
     "title": "Sync Failures",
     "type": "timeseries",
     "description": "Total number of target sync failures.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 56 },
     "targets": [
      {
       "expr": "increase(prometheus_target_sync_failed_total{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{scrape_job}}"
      }
     ]
    },
    {
     "title": "Scrape Pools Exceeded Limits",
     "type": "timeseries",
     "description": "Total number of times scrape pools hit the label limits, during sync or config reload.\n\nTotal number of times scrape pools hit the target limit, during sync or config reload.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(prometheus_target_scrape_pool_exceeded_label_limits_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Label Limit"
      },
      {
       "expr": "increase(prometheus_target_scrape_pool_exceeded_target_limit_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Target Limit"
      }
     ]
    },
    {
     "title": "Scrape Pool Reloads",
     "type": "timeseries",
     "description": "Total number of failed scrape pool reloads.\n\nTotal number of scrape pool reloads.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(prometheus_target_scrape_pool_reloads_failed_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Failures"
      },
      {
       "expr": "increase(prometheus_target_scrape_pool_reloads_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Reloads Total"
      }
     ]
    },
    {
     "title": "Scrape Pools Created",
     "type": "timeseries",
     "description": "Total number of scrape pool creations that failed.\n\nTotal number of scrape pool creation attempts.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(prometheus_target_scrape_pools_failed_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Failed"
      },
      {
       "expr": "increase(prometheus_target_scrape_pools_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Created"
      }
     ]
    },
    {
     "title": "Scrape Cache Flush Forced",
     "type": "timeseries",
     "description": "How many times a scrape cache was flushed due to getting big while scrapes are failing.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(prometheus_target_scrapes_cache_flush_forced_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Flush Forced"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Discovery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "File SD Timestamp (mtime)",
     "type": "table",
     "description": "Timestamp (mtime) of files read by FileSD. Timestamp is set at read time.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "label_replace(\n    prometheus_sd_file_mtime_seconds{instance=\"$node\"} * 1000,\n    \"filename\",\n    \"$1\",\n    \"filename\",\n    \".+/(.+)\"\n)"
      }
     ]
    },
    {
     "title": "Discovered Targets",
     "type": "timeseries",
     "description": "Current number of discovered targets.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
     "targets": [
      {
       "expr": "sum by (config) (prometheus_sd_discovered_targets{instance=\"$node\",name=\"scrape\"})",
       "legendFormat": "{{config}}"
      }
     ]
    },
    {
     "title": "Kubernetes SD Events",
     "type": "timeseries",
     "description": "The number of Kubernetes events handled.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
     "targets": [
      {
       "expr": "increase(prometheus_sd_kubernetes_events_total{instance=\"$node\"}[$__range])",
       "legendFormat": "{{event}} - {{role}}"
      }
     ]
    },
    {
     "title": "Service Discovery Duration Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(prometheus_sd_file_scan_duration_seconds{instance=\"$node\",quantile=\"0.5\"}[$__range]) > 0",
       "legendFormat": "File SD - 50th"
      },
      {
       "expr": "increase(prometheus_sd_file_scan_duration_seconds{instance=\"$node\",quantile=\"0.9\"}[$__range]) > 0",
       "legendFormat": "File SD - 90th"
      },
      {
       "expr": "increase(prometheus_sd_file_scan_duration_seconds{instance=\"$node\",quantile=\"0.99\"}[$__range]) > 0",
       "legendFormat": "File SD - 99th"
      },
      {
       "expr": "increase(prometheus_sd_kuma_fetch_duration_seconds{instance=\"$node\",quantile=\"0.5\"}[$__range]) > 0",
       "legendFormat": "KUMA - 50th"
      },
      {
       "expr": "increase(prometheus_sd_kuma_fetch_duration_seconds{instance=\"$node\",quantile=\"0.9\"}[$__range]) > 0",
       "legendFormat": "KUMA - 90th"
      },
      {
       "expr": "increase(prometheus_sd_kuma_fetch_duration_seconds{instance=\"$node\",quantile=\"0.99\"}[$__range]) > 0",
       "legendFormat": "KUMA - 99th"
      },
      {
       "expr": "sum by (call, endpoint) (increase(prometheus_sd_consul_rpc_duration_seconds{instance=\"$node\",quantile=\"0.5\"}[$__range])) > 0",
       "legendFormat": "{{call}}/{{endpoint}} - 50th"
      },
      {
       "expr": "sum by (call, endpoint) (increase(prometheus_sd_consul_rpc_duration_seconds{instance=\"$node\",quantile=\"0.9\"}[$__range])) > 0",
       "legendFormat": "{{call}}/{{endpoint}} - 90th"
      },
      {
       "expr": "sum by (call, endpoint) (increase(prometheus_sd_consul_rpc_duration_seconds{instance=\"$node\",quantile=\"0.99\"}[$__range])) > 0",
       "legendFormat": "{{call}}/{{endpoint}} - 99th"
      }
     ]
    },
    {
     "title": "Discovery Failures",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(prometheus_sd_consul_rpc_failures_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Consul Failures"
      },
      {
       "expr": "increase(prometheus_sd_dns_lookup_failures_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "DNS Lookup Failures"
      },
      {
       "expr": "increase(prometheus_sd_file_read_errors_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "File SD Errors"
      },
      {
       "expr": "increase(prometheus_sd_kuma_fetch_failures_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "KUMA Errors"
      }
     ]
    }
   ]
  },
  {
   "title": "Rules",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rule Group Last Evaluation Timestamp",
     "type": "table",
     "description": "The timestamp of the last rule group evaluation in seconds.",
     "gridPos": { "h": 6, "w": 15, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace(\n    prometheus_rule_group_last_evaluation_timestamp_seconds{instance=\"$node\"} * 1000,\n    \"rule_group\",\n    \"$1\",\n    \"rule_group\",\n    \".+;(.+)\"\n)",
       "legendFormat": "{{rule_group}}"
      },
      {
       "expr": "label_replace(\n    prometheus_rule_group_rules{instance=\"$node\"},\n    \"rule_group\",\n    \"$1\",\n    \"rule_group\",\n    \".+;(.+)\"\n)",
       "legendFormat": "{{rule_group}}"
      },
      {
       "expr": "label_replace(\n    prometheus_rule_group_interval_seconds{instance=\"$node\"},\n    \"rule_group\",\n    \"$1\",\n    \"rule_group\",\n    \".+;(.+)\"\n)",
       "legendFormat": "{{rule_group}}"
      }
     ]
    },
    {
     "title": "Rule Evaluations Samples Returned",
     "type": "timeseries",
     "description": "The number of samples returned during the last rule group evaluation",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\n    prometheus_rule_group_last_evaluation_samples{instance=\"$node\"},\n    \"rule_group\",\n    \"$1\",\n    \"rule_group\",\n    \".+;(.+)\"\n)",
       "legendFormat": "{{rule_group}}"
      }
     ]
    },
    {
     "title": "Rule Evaluation Duration",
     "type": "timeseries",
     "description": "The duration for a rule to execute.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "prometheus_rule_evaluation_duration_seconds{instance=\"$node\",quantile=\"0.5\"}",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "prometheus_rule_evaluation_duration_seconds{instance=\"$node\",quantile=\"0.9\"}",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "prometheus_rule_evaluation_duration_seconds{instance=\"$node\",quantile=\"0.99\"}",
       "legendFormat": "99th Percentile"
      }
     ]
    },
    {
     "title": "Rule Group Evaluation Duration",
     "type": "timeseries",
     "description": "The duration of rule group evaluations.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "prometheus_rule_group_duration_seconds{instance=\"$node\",quantile=\"0.5\"}",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "prometheus_rule_group_duration_seconds{instance=\"$node\",quantile=\"0.9\"}",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "prometheus_rule_group_duration_seconds{instance=\"$node\",quantile=\"0.99\"}",
       "legendFormat": "99th Percentile"
      }
     ]
    },
    {
     "title": "Rule Evaluations Duration",
     "type": "timeseries",
     "description": "The duration of the last rule group evaluation.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\n    prometheus_rule_group_last_duration_seconds{instance=\"$node\"},\n    \"rule_group\",\n    \"$1\",\n    \"rule_group\",\n    \".+;(.+)\"\n)",
       "legendFormat": "{{rule_group}}"
      }
     ]
    },
    {
     "title": "Rule Evaluation Failures",
     "type": "timeseries",
     "description": "The duration for a rule to execute.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\n    increase(prometheus_rule_evaluation_failures_total{instance=\"$node\"}[$__rate_interval]),\n    \"rule_group\",\n    \"$1\",\n    \"rule_group\",\n    \".+;(.+)\"\n)",
       "legendFormat": "{{rule_group}}"
      }
     ]
    },
    {
     "title": "Rule Evaluations Missed",
     "type": "timeseries",
     "description": "The total number of rule group evaluations missed due to slow rule group evaluation.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\n    increase(prometheus_rule_group_iterations_missed_total{instance=\"$node\"}[$__rate_interval]),\n    \"rule_group\",\n    \"$1\",\n    \"rule_group\",\n    \".+;(.+)\"\n)",
       "legendFormat": "{{rule_group}}"
      }
     ]
    },
    {
     "title": "Rule Group Iterations",
     "type": "timeseries",
     "description": "The total number of scheduled rule group evaluations, whether executed or missed.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\n    increase(prometheus_rule_group_iterations_total{instance=\"$node\"}[$__range]),\n    \"rule_group\",\n    \"$1\",\n    \"rule_group\",\n    \".+;(.+)\"\n)",
       "legendFormat": "{{rule_group}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Notifications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Alerts Dropped ",
     "type": "stat",
     "description": "Total number of alerts dropped due to errors when sending to Alertmanager.",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_notifications_dropped_total{instance=\"$node\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Notification Queue Saturation",
     "type": "gauge",
     "description": "The number of alert notifications in the queue. / The capacity of the alert notifications queue.",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_notifications_queue_length{instance=\"$node\"} \n/ \nprometheus_notifications_queue_capacity{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "Notifications Sent/sec",
     "type": "timeseries",
     "description": "Total number of alerts sent.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "label_replace(\n    rate(prometheus_notifications_sent_total{instance=\"$node\"}[$__rate_interval]),\n    \"alertmanager\",\n    \"$1\",\n    \"alertmanager\",\n    \"https?://([^/]+).+\"\n)",
       "legendFormat": "{{alertmanager}}"
      }
     ]
    },
    {
     "title": "Notification Latency - Percentiles",
     "type": "timeseries",
     "description": "Latency quantiles for sending alert notifications.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace(\n    prometheus_notifications_latency_seconds{instance=\"$node\",quantile=\"0.5\"},\n    \"alertmanager\",\n    \"$1\",\n    \"alertmanager\",\n    \"https?://([^/]+).+\"\n)",
       "legendFormat": "50th - {{alertmanager}}"
      },
      {
       "expr": "label_replace(\n    prometheus_notifications_latency_seconds{instance=\"$node\",quantile=\"0.9\"},\n    \"alertmanager\",\n    \"$1\",\n    \"alertmanager\",\n    \"https?://([^/]+).+\"\n)",
       "legendFormat": "90th - {{alertmanager}}"
      },
      {
       "expr": "label_replace(\n    prometheus_notifications_latency_seconds{instance=\"$node\",quantile=\"0.99\"},\n    \"alertmanager\",\n    \"$1\",\n    \"alertmanager\",\n    \"https?://([^/]+).+\"\n)",
       "legendFormat": "99th - {{alertmanager}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Handler Requests ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$handler - Request Times",
     "type": "heatmap",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
     "repeat": "handler",
     "targets": [
      {
       "expr": "sum by(le) (increase(prometheus_http_request_duration_seconds_bucket{instance=\"$node\"}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "$handler - Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 27 },
     "repeat": "handler",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (increase(prometheus_http_request_duration_seconds_bucket{instance=\"$node\"}[$__rate_interval])))",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (increase(prometheus_http_request_duration_seconds_bucket{instance=\"$node\"}[$__rate_interval])))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(prometheus_http_request_duration_seconds_bucket{instance=\"$node\"}[$__rate_interval])))",
       "legendFormat": "99th Percentile"
      }
     ]
    },
    {
     "title": "$handler - Response Codes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 27 },
     "repeat": "handler",
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(prometheus_http_requests_total{instance=\"$node\",handler=\"$handler\"}[$__rate_interval])",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "$handler - Response Sizes",
     "type": "heatmap",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
     "repeat": "handler",
     "targets": [
      {
       "expr": "sum by(le) (increase(prometheus_http_response_size_bytes_bucket{instance=\"$node\"}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Query Engine Duration ($slice) - Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
     "repeat": "slice",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_engine_query_duration_seconds{instance=\"$node\",slice=\"$slice\",quantile=\"0.5\"}[$__rate_interval])",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "rate(prometheus_engine_query_duration_seconds{instance=\"$node\",slice=\"$slice\",quantile=\"0.9\"}[$__rate_interval])",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "rate(prometheus_engine_query_duration_seconds{instance=\"$node\",slice=\"$slice\",quantile=\"0.99\"}[$__rate_interval])",
       "legendFormat": "99th Percentile"
      }
     ]
    }
   ]
  },
  {
   "title": "Remote",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Remote Storage Samples In/sec",
     "type": "timeseries",
     "description": "Samples in to remote storage, compare to samples out for queue managers.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_samples_in_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Samples In"
      }
     ]
    },
    {
     "title": "Strings Not Interned Released",
     "type": "timeseries",
     "description": "The number of times release has been called for strings that are not interned.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(prometheus_remote_storage_string_interner_zero_reference_releases_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "Releases"
      }
     ]
    },
    {
     "title": "Remote Read Queries",
     "type": "stat",
     "description": "The current number of remote read queries being executed or waiting.",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_api_remote_read_queries{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "Exemplars to Remote Storage",
     "type": "stat",
     "description": "Exemplars in to remote storage, compare to exemplars out for queue managers.",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_exemplars_in_total{instance=\"$node\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Highest Remote Storage Appender Timestamp",
     "type": "stat",
     "description": "Highest timestamp that has come into the remote storage via the Appender interface, in seconds since epoch.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_remote_storage_highest_timestamp_in_seconds{instance=\"$node\"} * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Process CPU Usage",
     "type": "gauge",
     "description": "Total user and system CPU time spent in seconds.",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{instance=\"$node\"}[$__rate_interval])  "
      }
     ]
    },
    {
     "title": "Open File Descriptors ",
     "type": "stat",
     "description": "Number of open file descriptors.",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_open_fds{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "FD Utilization",
     "type": "gauge",
     "description": "Number of open file descriptors / Maximum number of open file descriptors",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_open_fds{instance=\"$node\"} / process_max_fds{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "Process Resident Memory",
     "type": "stat",
     "description": "Resident memory size in bytes.",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "Process Virtual Memory",
     "type": "stat",
     "description": "Virtual memory size in bytes.",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "Process Uptime",
     "type": "stat",
     "description": "Start time of the process since unix epoch in seconds.",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 30 },
     "repeat": "node",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{instance=~\"$node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connection Tracking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "net_conntrack_dialer_conn_attempted_total",
     "type": "timeseries",
     "description": "Total number of connections attempted by the given dialer a given name.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "increase(net_conntrack_dialer_conn_attempted_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{dialer_name}}"
      }
     ]
    },
    {
     "title": "net_conntrack_dialer_conn_closed_total",
     "type": "timeseries",
     "description": "Total number of connections closed which originated from the dialer of a given name.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
     "targets": [
      {
       "expr": "increase(net_conntrack_dialer_conn_closed_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{dialer_name}}"
      }
     ]
    },
    {
     "title": "net_conntrack_dialer_conn_established_total",
     "type": "timeseries",
     "description": "Total number of connections successfully established by the given dialer a given name.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
     "targets": [
      {
       "expr": "increase(net_conntrack_dialer_conn_established_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{dialer_name}}"
      }
     ]
    },
    {
     "title": "net_conntrack_dialer_conn_failed_total",
     "type": "timeseries",
     "description": "Total number of connections failed to dial by the dialer a given name.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "sum by (dialer_name, reason) (increase(net_conntrack_dialer_conn_failed_total{instance=\"$node\"}[$__rate_interval])) ",
       "legendFormat": "{{dialer_name}} - {{reason}}"
      }
     ]
    },
    {
     "title": "Listener Accepted and Closed Connections",
     "type": "timeseries",
     "description": "Total number of connections opened to the listener of a given name.\n\nTotal number of connections closed that were made to the listener of a given name.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(net_conntrack_listener_conn_accepted_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{listener_name}} - open"
      },
      {
       "expr": "increase(net_conntrack_listener_conn_closed_total{instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{listener_name}} - closed"
      }
     ]
    }
   ]
  }
 ]
}