{
 "title": "Prometheus Alerts",
 "tags": [
  "prometheus",
  "alerts",
  "alerting"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": {
     "query": "label_values(ALERTS, cluster_name)"
    }
   },
   { "name": "node", "label": "Node", "query": { "query": "label_values(ALERTS, instance)" } },
   { "name": "category", "label": "Category", "query": { "query": "label_values(ALERTS, category)" } },
   { "name": "severity", "label": "Severity", "query": { "query": "label_values(ALERTS, severity)" } }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Alerts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    ALERTS{alertstate=\"firing\",cluster_name=~\"$cluster_name\",category=~\"$category\",severity=~\"$severity\"}\n    or\n    ALERTS{alertstate=\"firing\",instance=~\"$node\",category=~\"$category\",severity=~\"$severity\"}\n)",
     "legendFormat": "Alerts"
    }
   ]
  },
  {
   "title": "Pending Alerts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    ALERTS{alertstate=\"pending\",cluster_name=~\"$cluster_name\",category=~\"$category\",severity=~\"$severity\"}\n    or\n    ALERTS{alertstate=\"pending\",instance=~\"$node\",category=~\"$category\",severity=~\"$severity\"}\n)",
     "legendFormat": "Alerts"
    }
   ]
  },
  {
   "title": "Active Alerts by Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    ALERTS{alertstate=\"firing\",cluster_name=~\"$cluster_name\",category=~\"$category\",severity=~\"$severity\"}\n    or\n    ALERTS{alertstate=\"firing\",instance=~\"$node\",category=~\"$category\",severity=~\"$severity\"}\n) by (alertname)",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "Active Alerts by Severity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    ALERTS{alertstate=\"firing\",cluster_name=~\"$cluster_name\",category=~\"$category\",severity=~\"$severity\"}\n    or\n    ALERTS{alertstate=\"firing\",instance=~\"$node\",category=~\"$category\",severity=~\"$severity\"}\n) by (severity)",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "Active Alerts by Category",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    ALERTS{alertstate=\"firing\",cluster_name=~\"$cluster_name\",category=~\"$category\",severity=~\"$severity\"}\n    or\n    ALERTS{alertstate=\"firing\",instance=~\"$node\",category=~\"$category\",severity=~\"$severity\"}\n) by (category)",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "Active Alerts by Cluster",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    ALERTS{alertstate=\"firing\",cluster_name=~\"$cluster_name\",category=~\"$category\",severity=~\"$severity\"}\n) by (cluster_name)",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "Alerts by Type ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (alertname) (\n    ALERTS{alertstate=\"firing\",cluster_name=~\"$cluster_name\",category=~\"$category\",severity=~\"$severity\"}\n    or\n    ALERTS{alertstate=\"firing\",instance=~\"$node\",category=~\"$category\",severity=~\"$severity\"}\n)",
     "legendFormat": "{{alertstate}}"
    }
   ]
  },
  {
   "title": "Alerts by State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (alertstate) (\n    ALERTS{cluster_name=~\"$cluster_name\",category=~\"$category\",severity=~\"$severity\"}\n    or\n    ALERTS{instance=~\"$node\",category=~\"$category\",severity=~\"$severity\"}\n)",
     "legendFormat": "{{alertstate}}"
    }
   ]
  },
  {
   "title": "Alerts by Cluster ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (cluster_name) (\n    ALERTS{alertstate=\"firing\",cluster_name=~\"$cluster_name\",category=~\"$category\",severity=~\"$severity\"}\n)",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Alerts by Category ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (category) (\n    ALERTS{alertstate=\"firing\",cluster_name=~\"$cluster_name\",category=~\"$category\",severity=~\"$severity\"}\n    or\n    ALERTS{alertstate=\"firing\",instance=~\"$node\",category=~\"$category\",severity=~\"$severity\"}\n)",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Alerts Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "count(\n    ALERTS{alertstate=\"firing\",cluster_name=~\"$cluster_name\",category=~\"$category\",severity=~\"$severity\"}\n    or\n    ALERTS{alertstate=\"firing\",instance=~\"$node\",category=~\"$category\",severity=~\"$severity\"}\n) by (alertname, cluster_name, instance, category, severity)",
     "legendFormat": "Alerts Count"
    },
    {
     "expr": "max(\n    time() - ALERTS_FOR_STATE{cluster_name=~\"$cluster_name\",category=~\"$category\",severity=~\"$severity\"}\n    or  \n    time() - ALERTS_FOR_STATE{instance=~\"$node\",category=~\"$category\",severity=~\"$severity\"}\n) by (alertname, cluster_name, instance, category, severity)",
     "legendFormat": "Alerting For"
    }
   ]
  }
 ]
}