{
 "title": "Couchbase Logs - Query Logs Overview",
 "description": "A Dashboard to allow easy search of the Couchbase slow query logs ",
 "tags": [
  "couchbase",
  "n1ql",
  "query",
  "slow-query",
  "logs",
  "loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({file=\"slow_query.log\"}, couchbase_cluster_name)"
   },
   {
    "name": "level",
    "label": "Level",
    "query": "label_values({couchbase_cluster_name=\"$cluster\",bucket=~\"$bucket\",file=\"slow_query.log\"}, level)"
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": "label_values({couchbase_cluster_name=\"$cluster\",level=~\"$level\",node=~\"$node\",file=\"slow_query.log\"}, bucket)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values({couchbase_cluster_name=\"$cluster\",bucket=~\"$bucket\",level=~\"$level\",file=\"slow_query.log\"}, couchbase_node)"
   },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Logs Matching",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=~\"$level\", bucket=~\"$bucket\"}\n    |~ \"$search\"  [$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Buckets Matching",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count by(bucket) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=~\"$level\", bucket=~\"$bucket\"}\n    |~ \"$search\"  [$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Users Matching",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count by(users) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", bucket=~\"$bucket\"} \n    |~ \"$search\" [$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Remote Addresses Matching",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count by(remoteAddr) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", bucket=~\"$bucket\"} \n    | json \n    | label_format remoteAddr=`{{ regexReplaceAll \":[0-9]+\" .remoteAddr \"\" }}`\n    |~ \"$search\" [$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Slow Query Logs ",
   "type": "logs",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=~\"$level\", bucket=~\"$bucket\"} |~ \"$search\""
    }
   ]
  }
 ]
}