{
 "title": "Couchbase Logs - Slow Queries Overview",
 "description": "A Couchbase Slow Queries Dashboard for Loki",
 "tags": [
  "couchbase",
  "n1ql",
  "slow-query",
  "troubleshooting",
  "logs",
  "loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({file=\"slow_query.log\"}, couchbase_cluster_name)"
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": "label_values({couchbase_cluster_name=\"$cluster\",file=\"slow_query.log\"}, bucket)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values({couchbase_cluster_name=\"$cluster\",file=\"slow_query.log\"}, couchbase_node)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "top", "label": "Top", "query": "10,25,50,100" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Count of Slow Queries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=\"INFO\", bucket=~\"$bucket\"} [$__range]\n  )\n)",
     "legendFormat": "{{bucket}}",
     "resolution": 5
    }
   ]
  },
  {
   "title": "Slow Queries by Users",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(users) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", couchbase_node=~\"$node\", bucket=~\"$bucket\"} \n    | json\n    | __error__=\"\" [$__range]\n  )\n)",
     "legendFormat": "{{ users }}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Slow Queries by Remote Address",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(remoteAddr) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", bucket=~\"$bucket\"} \n    | json \n    | label_format remoteAddr=`{{ regexReplaceAll \":[0-9]+\" .remoteAddr \"\" }}`\n    | __error__=\"\" [$__range]\n  )\n)",
     "legendFormat": "{{ remoteAddr }}"
    }
   ]
  },
  {
   "title": "Slow Queries by SDK",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(userAgent) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", bucket=~\"$bucket\", couchbase_node=~\"$node\"} \n    | json \n    | label_format userAgent=`{{ regexReplaceAll \"\\\\s.+\" .userAgent \"\" }}`\n    | __error__=\"\" [$__range]\n  )\n)",
     "legendFormat": "{{ userAgent }}"
    }
   ]
  },
  {
   "title": "Avg. Query Selectivity",
   "type": "gauge",
   "description": "The Query Selectivity is the # of Results / # of Index Scan Results, this should be as close to 100% as possible",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (\n  avg_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=\"INFO\", bucket=~\"$bucket\", couchbase_node=~\"$node\"}\n    | json \n    | unwrap querySelectivityPercent \n    | errorCount == 0 [$__range]\n  )\n)",
     "resolution": 10
    }
   ]
  },
  {
   "title": "Avg. Slow Query Response Bytes ",
   "type": "stat",
   "description": "Avg. Bytes for All Slow Queries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (\n  avg_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=\"INFO\", bucket=~\"$bucket\", couchbase_node=~\"$node\"}\n    | json \n    | unwrap resultSize \n    | __error__=\"\" [$interval]\n  )\n)",
     "legendFormat": "{{bucket}}",
     "resolution": 10
    }
   ]
  },
  {
   "title": "Avg. Slow Query Result Count",
   "type": "stat",
   "description": "Average Results sent back to client",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (\n  avg_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=\"INFO\", bucket=~\"$bucket\", couchbase_node=~\"$node\"}\n    | json \n    | unwrap resultCount \n    | __error__=\"\" [$interval]\n  )\n)",
     "legendFormat": "{{bucket}}",
     "resolution": 10
    }
   ]
  },
  {
   "title": "Avg. Slow Query Index Scan Results",
   "type": "stat",
   "description": "The Average number of items returned from index scan operation",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (\n  avg_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=\"INFO\", bucket=~\"$bucket\", couchbase_node=~\"$node\"}\n    | json \n    | unwrap phaseCounts_indexScan \n    | __error__=\"\" [$interval]\n  )\n)",
     "legendFormat": "{{bucket}}",
     "resolution": 10
    }
   ]
  },
  {
   "title": "Avg. Slow Query Response Time",
   "type": "stat",
   "description": "Avg. Response Time of Slow Queries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (\n  avg_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=\"INFO\", bucket=~\"$bucket\", couchbase_node=~\"$node\"}\n    | json \n    | unwrap elapsedTimeMs \n    | errorCount == 0 [$interval]\n  )\n)",
     "legendFormat": "{{bucket}}",
     "resolution": 10
    }
   ]
  },
  {
   "title": "Avg. Documents Fetched",
   "type": "stat",
   "description": "The average number of documents fetched for each query ",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (\n  avg_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=\"INFO\", bucket=~\"$bucket\", couchbase_node=~\"$node\"}\n    | json \n    | unwrap phaseCounts_fetch \n    | errorCount == 0 [$interval]\n  )\n)",
     "legendFormat": "{{bucket}}",
     "resolution": 10
    }
   ]
  },
  {
   "title": "Slow Queries - Bucket Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slow Queries by Bucket",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(bucket) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", bucket=~\"$bucket\"} [$__range]\n  )\n)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Query Errors by Bucket",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (bucket) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=\"INFO\", bucket=~\"$bucket\"} \n    | json \n    | errorCount > 0 [$__range]\n  )\n)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Count of Slow Queries by Bucket",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (bucket) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=\"INFO\", bucket=~\"$bucket\"} [$interval]\n  )\n)",
       "legendFormat": "{{bucket}}",
       "resolution": 5
      }
     ]
    },
    {
     "title": "Slow Query Document Fetches by Bucket",
     "type": "timeseries",
     "description": "Sum of all fetch operations caused by the slow query ",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (bucket) (\n  sum_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=\"INFO\", bucket=~\"$bucket\"}\n    | json \n    | unwrap phaseCounts_fetch \n    | __error__=\"\" [$interval]\n  )\n)",
       "legendFormat": "{{bucket}}",
       "resolution": 5
      }
     ]
    },
    {
     "title": "Slow Query Response Bytes by Bucket",
     "type": "timeseries",
     "description": "Sum of all fetch operations caused by the slow query ",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (bucket) (\n  sum_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=\"INFO\", bucket=~\"$bucket\"}\n    | json \n    | unwrap resultSize \n    | __error__=\"\" [$interval]\n  )\n)",
       "legendFormat": "{{bucket}}",
       "resolution": 5
      }
     ]
    },
    {
     "title": "Avg. Slow Query Selectivity  by Bucket",
     "type": "timeseries",
     "description": "The Average Query Selectivity Percentage by Bucket",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (bucket) (\n  avg_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=\"INFO\", bucket=~\"$bucket\"}\n    | json \n    | unwrap querySelectivityPercent \n    | __error__=\"\" [$interval]\n  )\n)",
       "legendFormat": "{{bucket}}",
       "resolution": 5
      }
     ]
    },
    {
     "title": "Avg. Slow Query Elapsed Time  by Bucket",
     "type": "timeseries",
     "description": "Sum of all fetch operations caused by the slow query ",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (bucket) (\n  avg_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=\"INFO\", bucket=~\"$bucket\"}\n    | json \n    | unwrap elapsedTimeMs \n    | __error__=\"\" [$interval]\n  )\n)",
       "legendFormat": "{{bucket}}",
       "resolution": 5
      }
     ]
    }
   ]
  },
  {
   "title": "Top $top - Most Frequent Slow Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $top - Most Frequent Slow Queries",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "topk(\n  $top,\n  sum by (bucket, scope, collection, users, statement) (\n    count_over_time(\n      {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=\"INFO\", bucket=~\"$bucket\"} \n      | json\n      [$__range]\n    )\n  )\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "Top $top - Longest Running (elapsedTime) Slow Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $top - Longest Running (elapsedTime) Slow Queries",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "topk(\n  $top, \n  max_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=\"INFO\", bucket=~\"$bucket\"} \n    | json \n    | unwrap elapsedTimeMs\n    | __error__=\"\"[$__range]\n  )\n  by (bucket, scope, collection, users, statement)\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "Top $top - Primary Index Scan Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $top - Primary Index Scan Queries",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "topk(\n  $top,\n  sum by (bucket, scope, collection, users, statement) (\n    count_over_time(\n      {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=\"INFO\", bucket=~\"$bucket\"} \n      | json \n      | phaseCounts_primaryScan > 0\n      [$__range]\n    )\n  )\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "Top $top - Highest Cost Slow Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $top - Highest Cost Slow Queries",
     "type": "table",
     "description": "Highest Cost Queries are a sum of all of the Phase Counts",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "topk(\n  $top, \n  avg_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=\"INFO\", bucket=~\"$bucket\"} \n    | json \n    | unwrap cost\n    | __error__=\"\"[$__range]\n  )\n  by (bucket, scope, collection, users, statement)\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "Top $top - Lowest Selectivity Slow Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $top - Lowest Selectivity Slow Queries",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "bottomk(\n  $top, \n  max_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=\"INFO\", bucket=~\"$bucket\"} \n    | json \n    | unwrap querySelectivityPercent\n    | __error__=\"\"[$__range]\n  )\n  by (bucket, scope, collection, users, statement)\n)"
      }
     ]
    }
   ]
  }
 ]
}