{
 "title": "Couchbase Logs - Slow Query Log Viewer",
 "description": "A Dashboard to allow easy search of the Couchbase slow query logs ",
 "tags": [
  "couchbase",
  "n1ql",
  "query",
  "slow-query",
  "logs",
  "loki"
 ],
 "time": { "from": "2022-08-30T15:25:37.994Z", "to": "2022-08-30T16:25:37.994Z" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({file=\"slow_query.log\"}, couchbase_cluster_name)"
   },
   {
    "name": "level",
    "label": "Level",
    "query": "label_values({couchbase_cluster_name=\"$cluster\",file=\"slow_query.log\"}, level)"
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": "label_values({couchbase_cluster_name=\"$cluster\",level=~\"$level\",file=\"slow_query.log\"}, bucket)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values({couchbase_cluster_name=\"$cluster\",bucket=~\"$bucket\",level=~\"$level\",file=\"slow_query.log\"}, couchbase_node)"
   },
   { "name": "search", "label": "Search" },
   { "name": "user", "label": "User" }
  ]
 },
 "panels": [
  {
   "title": "Logs Matching",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=~\"$level\", bucket=~\"$bucket\", couchbase_node=~\"$node\"}\n    |~ \"(?i)$search\"\n    | json \n    | users=~\"(?i)$user.*\"\n    | __error__=\"\" [$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Buckets Matching",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(bucket) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", bucket=~\"$bucket\"}\n    |~ \"(?i)$search\"\n    | json \n    | users=~\"(?i)$user.*\"\n    | __error__=\"\" [$__range]\n  )\n)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Users Matching",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(users) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", bucket=~\"$bucket\"}\n    |~ \"(?i)$search\"\n    | json \n    | users=~\"(?i)$user.*\"\n    | __error__=\"\" [$__range]\n  )\n)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Remote Addresses  Matching",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(remoteAddr) (\n  count_over_time(\n    {couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", bucket=~\"$bucket\"}\n    |~ \"(?i)$search\"\n    | json \n    | users=~\"(?i)$user.*\"\n    | label_format remoteAddr=`{{ regexReplaceAll \":[0-9]+$\" .remoteAddr \"\" }}`\n    | __error__=\"\" [$__range]\n  )\n)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Slow Query Logs ",
   "type": "logs",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{couchbase_cluster_name=\"$cluster\", file=\"slow_query.log\", level=~\"$level\", bucket=~\"$bucket\", couchbase_node=~\"$node\"} \n|~ \"(?i)$search\""
    }
   ]
  }
 ]
}